import type { FdeAgentCatalogItem } from "@/feature/fde/types";

/**
 * FDE 专家广场商品源。
 */
export const FDE_AGENT_CATALOG_ITEMS: FdeAgentCatalogItem[] = [
  {
    id: "agent-public-01",
    name: "AI CEO 教练",
    releaseVersion: "v2.4.1",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "待企业配置权限范围。",
    scope: "public",
    sceneCategory: "经营管理",
    description: "适合老板经营复盘、管理动作生成和跨部门协同建议。",
  },
  {
    id: "agent-public-02",
    name: "招聘协同官",
    releaseVersion: "v1.9.0",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "适合 HR 与业务负责人协同使用。",
    scope: "public",
    sceneCategory: "组织协同",
    description: "适合招聘推进、面试反馈归纳和候选人协同。",
  },
  {
    id: "agent-public-03",
    name: "门店经营日报官",
    releaseVersion: "v1.8.3",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "建议绑定门店经营数据后开放给管理层。",
    scope: "public",
    sceneCategory: "经营管理",
    description: "适合门店营收汇总、日结日报和经营异常提醒。",
  },
  {
    id: "agent-public-04",
    name: "供应链异常雷达",
    releaseVersion: "v2.0.2",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "建议与库存、采购数据联动后使用。",
    scope: "public",
    sceneCategory: "供应链",
    description: "适合库存预警、交付延迟和补货建议。",
  },
  {
    id: "agent-public-05",
    name: "财务对账助手",
    releaseVersion: "v1.6.8",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "建议开放给财务负责人和门店会计使用。",
    scope: "public",
    sceneCategory: "经营管理",
    description: "适合账单核对、异常流水归因和门店财务周报整理。",
  },
  {
    id: "agent-public-06",
    name: "经营波动分析师",
    releaseVersion: "v1.4.5",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "适合经营负责人查看门店波动和原因归纳。",
    scope: "public",
    sceneCategory: "经营管理",
    description: "适合日销、毛利、退货和活动表现波动的结构化分析。",
  },
  {
    id: "agent-public-07",
    name: "面试复盘官",
    releaseVersion: "v1.3.9",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "建议面试官和 HRBP 协同使用。",
    scope: "public",
    sceneCategory: "组织协同",
    description: "适合沉淀面试纪要、总结面试结论和输出候选人评估摘要。",
  },
  {
    id: "agent-public-08",
    name: "绩效诊断官",
    releaseVersion: "v1.2.7",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "建议管理层和 HRBP 在绩效评审前使用。",
    scope: "public",
    sceneCategory: "组织协同",
    description: "适合绩效波动诊断、中层表现总结和人员风险预警。",
  },
  {
    id: "agent-public-09",
    name: "采购补货官",
    releaseVersion: "v1.7.1",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "建议采购与仓配团队配合使用。",
    scope: "public",
    sceneCategory: "供应链",
    description: "适合采购建议、补货节奏安排和缺货风险提前预警。",
  },
  {
    id: "agent-public-10",
    name: "履约监控官",
    releaseVersion: "v1.5.6",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "适合履约团队做时效巡检和异常分单。",
    scope: "public",
    sceneCategory: "供应链",
    description: "适合订单发货监控、履约延误识别和售后风险提醒。",
  },
  {
    id: "agent-public-11",
    name: "销售线索官",
    releaseVersion: "v1.6.2",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "适合销售负责人和业务拓展团队使用。",
    scope: "public",
    sceneCategory: "销售增长",
    description: "适合线索分级、客户跟进提醒和成交机会归纳。",
  },
  {
    id: "agent-public-12",
    name: "复购运营官",
    releaseVersion: "v1.3.4",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "适合会员运营和私域团队联动使用。",
    scope: "public",
    sceneCategory: "销售增长",
    description: "适合老客唤醒、复购活动建议和用户分层运营。",
  },
  {
    id: "agent-public-13",
    name: "客服质检官",
    releaseVersion: "v1.4.9",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "适合客服主管和售后团队质检使用。",
    scope: "public",
    sceneCategory: "客户服务",
    description: "适合客服会话质检、投诉归因和服务问题归纳。",
  },
  {
    id: "agent-public-14",
    name: "工单流转官",
    releaseVersion: "v1.2.6",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "适合售后和服务交付团队跟踪工单。",
    scope: "public",
    sceneCategory: "客户服务",
    description: "适合服务工单分派、流转提醒和超时节点追踪。",
  },
  {
    id: "agent-public-15",
    name: "库存盘点助手",
    releaseVersion: "v1.1.8",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "适合仓库主管和门店盘点负责人使用。",
    scope: "public",
    sceneCategory: "供应链",
    description: "适合盘点差异归纳、库存健康检查和异常门店提示。",
  },
  {
    id: "agent-public-16",
    name: "经营复盘助手",
    releaseVersion: "v1.9.4",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "适合老板和经营管理层做周期复盘。",
    scope: "public",
    sceneCategory: "经营管理",
    description: "适合周经营复盘、关键指标总结和经营动作建议。",
  },
  {
    id: "agent-public-17",
    name: "门店巡检助手",
    releaseVersion: "v1.3.2",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "适合区域督导和门店负责人配合使用。",
    scope: "public",
    sceneCategory: "经营管理",
    description: "适合巡店记录沉淀、问题归类和整改动作跟进。",
  },
  {
    id: "agent-public-18",
    name: "直播复盘官",
    releaseVersion: "v1.2.9",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "适合直播运营和品牌方复盘使用。",
    scope: "public",
    sceneCategory: "销售增长",
    description: "适合直播数据复盘、商品表现归因和下轮排期建议。",
  },
  {
    id: "agent-public-19",
    name: "售后满意度官",
    releaseVersion: "v1.1.7",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "适合客服主管和服务交付团队使用。",
    scope: "public",
    sceneCategory: "客户服务",
    description: "适合用户评价归纳、售后体验总结和高频问题沉淀。",
  },
  {
    id: "agent-public-20",
    name: "采购价格观察员",
    releaseVersion: "v1.0.8",
    sourceLabel: "公共广场",
    statusLabel: "待下发",
    permissionHint: "适合采购团队做价格波动追踪。",
    scope: "public",
    sceneCategory: "供应链",
    description: "适合供应商价格波动识别、比价提醒和进货窗口建议。",
  },
  {
    id: "agent-mine-01",
    name: "零售试点复盘师",
    releaseVersion: "v0.9.6",
    sourceLabel: "我的 Agent",
    statusLabel: "待下发",
    permissionHint: "当前 FDE 自定义版本，仅对试点租户开放。",
    scope: "mine",
    sceneCategory: "客户专属",
    description: "适合首批零售试点客户做经营复盘和门店周报。",
  },
  {
    id: "agent-mine-02",
    name: "组织试点陪跑官",
    releaseVersion: "v0.8.4",
    sourceLabel: "我的 Agent",
    statusLabel: "待下发",
    permissionHint: "适合组织管理试点客户做专项交付。",
    scope: "mine",
    sceneCategory: "交付专属",
    description: "适合组织管理、招聘协同和部门试点陪跑。",
  },
  {
    id: "agent-mine-03",
    name: "电商运营陪跑官",
    releaseVersion: "v0.7.9",
    sourceLabel: "我的 Agent",
    statusLabel: "待下发",
    permissionHint: "适合电商商家试点租户做专项交付。",
    scope: "mine",
    sceneCategory: "试点扩展",
    description: "适合选品、投放、店铺经营试点的专项支持。",
  },
  {
    id: "agent-mine-04",
    name: "零售晨会陪跑官",
    releaseVersion: "v0.8.9",
    sourceLabel: "我的 Agent",
    statusLabel: "待下发",
    permissionHint: "适合零售客户日会播报和店长跟进场景。",
    scope: "mine",
    sceneCategory: "客户专属",
    description: "适合串联晨会播报、昨日经营复盘和今日动作提醒。",
  },
  {
    id: "agent-mine-05",
    name: "招聘面板复盘官",
    releaseVersion: "v0.8.2",
    sourceLabel: "我的 Agent",
    statusLabel: "待下发",
    permissionHint: "适合招聘专项交付，聚焦岗位漏斗复盘。",
    scope: "mine",
    sceneCategory: "交付专属",
    description: "适合招聘看板搭建、岗位漏斗分析和招聘周报整理。",
  },
  {
    id: "agent-mine-06",
    name: "店仓补货排班官",
    releaseVersion: "v0.7.4",
    sourceLabel: "我的 Agent",
    statusLabel: "待下发",
    permissionHint: "适合零售和电商试点客户联动仓配与门店。",
    scope: "mine",
    sceneCategory: "试点扩展",
    description: "适合门店缺货补货、人员排班建议和高峰时段预排。",
  },
  {
    id: "agent-mine-07",
    name: "财务口径校对官",
    releaseVersion: "v0.6.8",
    sourceLabel: "我的 Agent",
    statusLabel: "待下发",
    permissionHint: "适合财务试点客户做口径梳理和异常复核。",
    scope: "mine",
    sceneCategory: "客户专属",
    description: "适合财务对账口径校对、跨表差异说明和报表一致性复核。",
  },
  {
    id: "agent-mine-08",
    name: "门店巡店记录官",
    releaseVersion: "v0.7.2",
    sourceLabel: "我的 Agent",
    statusLabel: "待下发",
    permissionHint: "适合零售客户巡店和现场问题记录。",
    scope: "mine",
    sceneCategory: "客户专属",
    description: "适合巡店纪要沉淀、现场问题汇总和整改动作同步。",
  },
  {
    id: "agent-mine-09",
    name: "交付验收陪跑官",
    releaseVersion: "v0.6.9",
    sourceLabel: "我的 Agent",
    statusLabel: "待下发",
    permissionHint: "适合首期交付客户做验收陪跑和培训。",
    scope: "mine",
    sceneCategory: "交付专属",
    description: "适合交付验收、培训任务梳理和问题闭环记录。",
  },
  {
    id: "agent-mine-10",
    name: "客服回访陪跑官",
    releaseVersion: "v0.6.5",
    sourceLabel: "我的 Agent",
    statusLabel: "待下发",
    permissionHint: "适合客户试点期做回访跟进和满意度追踪。",
    scope: "mine",
    sceneCategory: "交付专属",
    description: "适合回访记录、问题归档和试点反馈整理。",
  },
  {
    id: "agent-mine-11",
    name: "销售跟单陪跑官",
    releaseVersion: "v0.5.8",
    sourceLabel: "我的 Agent",
    statusLabel: "待下发",
    permissionHint: "适合销售试点客户做跟单提醒和机会归纳。",
    scope: "mine",
    sceneCategory: "试点扩展",
    description: "适合跟单节奏提醒、客户阶段总结和成交机会提示。",
  },
  {
    id: "agent-mine-12",
    name: "服务质检试点官",
    releaseVersion: "v0.5.2",
    sourceLabel: "我的 Agent",
    statusLabel: "待下发",
    permissionHint: "适合客服与服务质检试点客户专项交付。",
    scope: "mine",
    sceneCategory: "试点扩展",
    description: "适合会话质检、服务抽检和投诉问题专项分析。",
  },
  {
    id: "agent-mine-13",
    name: "零售督导陪跑官",
    releaseVersion: "v0.9.1",
    sourceLabel: "我的 Agent",
    statusLabel: "待下发",
    permissionHint: "适合零售交付客户做督导巡店和整改跟进。",
    scope: "mine",
    sceneCategory: "交付专属",
    description: "适合首批门店试点客户做督导陪跑和现场问题跟踪。",
  },
  {
    id: "agent-mine-14",
    name: "客服升级试点官",
    releaseVersion: "v0.8.6",
    sourceLabel: "我的 Agent",
    statusLabel: "待下发",
    permissionHint: "适合服务质检客户做专项交付试点。",
    scope: "mine",
    sceneCategory: "试点扩展",
    description: "适合售后升级项目，辅助梳理工单问题和服务改进动作。",
  },
];
