import type {
  FdeDeliveryOrderItem,
  FdeDeliveryStepItem,
  FdeEvolutionTaskItem,
  FdeFeedbackAgentItem,
  FdeLeadFormState,
  FdeLeadItem,
  FdeOperationsCustomerItem,
  FdeOpportunityItem,
  FdeTeamMemberItem,
  FdeWorkbenchTabItem,
} from "@/feature/fde/types";

/**
 * FDE 工作台导航。
 */
export const FDE_WORKBENCH_TABS: FdeWorkbenchTabItem[] = [
  { key: "opportunities", label: "商机工作台", description: "团队商机与转化漏斗" },
  { key: "leads", label: "线索工单", description: "线索录入、分配与状态流转" },
  { key: "delivery", label: "配置交付", description: "正式订单交付与专家团配置" },
  { key: "operations", label: "运营监控", description: "客户 AI 专家团实时运行状态" },
  { key: "feedback", label: "数据回流看板", description: "按 Agent 查看回流数据与进化建议" },
  { key: "evolution", label: "进化任务管理", description: "训练中与待审核的进化任务" },
];

/**
 * FDE 交付步骤。
 */
export const FDE_DELIVERY_STEPS: FdeDeliveryStepItem[] = [
  { key: "customerConfirm", label: "客户租户创建" },
  { key: "deviceConfig", label: "设备配置" },
  { key: "agentConfig", label: "Agent配置" },
  { key: "apiTest", label: "初始化测试" },
  { key: "preflight", label: "发货前检查" },
];

/**
 * FDE 团队成员。
 */
export const FDE_TEAM_MEMBERS: FdeTeamMemberItem[] = [
  {
    id: "fde-leader-wanglin",
    name: "王琳",
    title: "FDE 团队负责人",
    role: "leader",
    status: "online",
    focusScenes: ["商机诊断", "交付策略", "版本审核"],
    avatarSeed: "wang-lin",
  },
  {
    id: "fde-engineer-chenlan",
    name: "陈岚",
    title: "资深交付工程师",
    role: "engineer",
    status: "online",
    focusScenes: ["经营管理", "销售增长", "数据回流"],
    avatarSeed: "chen-lan",
  },
  {
    id: "fde-engineer-luzhou",
    name: "陆舟",
    title: "FDE 配置工程师",
    role: "engineer",
    status: "busy",
    focusScenes: ["内容创作", "本地设备部署", "版本灰度"],
    avatarSeed: "lu-zhou",
  },
  {
    id: "fde-engineer-hejin",
    name: "何晋",
    title: "FDE 运营工程师",
    role: "engineer",
    status: "online",
    focusScenes: ["客户服务", "线索工单", "运营监控"],
    avatarSeed: "he-jin",
  },
];

/**
 * FDE 商机数据。
 */
export const FDE_OPPORTUNITIES: FdeOpportunityItem[] = [
  {
    id: "opp-01",
    companyName: "智联制造",
    scenarioName: "经营日报 + 门店动作同步",
    industry: "制造零售",
    stage: "初步沟通",
    amountWan: 18.8,
    winRate: 32,
    ownerId: "fde-engineer-chenlan",
    nextAction: "安排老板演示经营日报链路",
    nextActionDate: "2026-03-31",
    source: "官网咨询",
    summary: "对门店日报、排班和缺货风险特别关注。",
  },
  {
    id: "opp-02",
    companyName: "环球电商",
    scenarioName: "基于 VOC 的产品创新",
    industry: "跨境电商",
    stage: "产品演示",
    amountWan: 26.5,
    winRate: 52,
    ownerId: "fde-engineer-luzhou",
    nextAction: "补演 VOC 看板和产品创新节奏",
    nextActionDate: "2026-04-02",
    source: "FDE 服务页",
    summary: "老板希望先用评论和竞品动态跑通新品会决策。",
  },
  {
    id: "opp-03",
    companyName: "创新医疗",
    scenarioName: "销售线索分层 + 战报推送",
    industry: "医疗服务",
    stage: "方案推荐",
    amountWan: 34.2,
    winRate: 63,
    ownerId: "fde-engineer-chenlan",
    nextAction: "输出正式方案和设备部署说明",
    nextActionDate: "2026-03-30",
    source: "老板转介绍",
    summary: "重点看多院区销售协同和一线跟进质检。",
  },
  {
    id: "opp-04",
    companyName: "新锐科技",
    scenarioName: "招聘协同 + 组织风险预警",
    industry: "科技服务",
    stage: "商务谈判",
    amountWan: 19.7,
    winRate: 84,
    ownerId: "fde-engineer-hejin",
    nextAction: "确认采购清单与本地设备数量",
    nextActionDate: "2026-03-29",
    source: "线下活动",
    summary: "已确认试点部门和 PO，进入商务条款确认。",
  },
  {
    id: "opp-05",
    companyName: "百汇零售",
    scenarioName: "门店经营日清 + 财务对账",
    industry: "零售连锁",
    stage: "已成交",
    amountWan: 49.0,
    winRate: 100,
    ownerId: "fde-engineer-chenlan",
    nextAction: "进入配置交付与设备发货",
    nextActionDate: "2026-03-28",
    source: "官网咨询",
    summary: "签约首期 28 家门店，FDE 已进入设备配置阶段。",
  },
  {
    id: "opp-06",
    companyName: "极客供应链",
    scenarioName: "供应链异常预警 + 补位建议",
    industry: "供应链",
    stage: "产品演示",
    amountWan: 22.4,
    winRate: 45,
    ownerId: "fde-engineer-hejin",
    nextAction: "安排对接 ERP 与库存 API",
    nextActionDate: "2026-04-01",
    source: "FDE 服务页",
    summary: "需要把采购、库存和交付预警汇成一套 AI 协作流。",
  },
];

/**
 * FDE 线索工单数据。
 */
export const FDE_LEADS: FdeLeadItem[] = [
  {
    id: "lead-01",
    companyName: "某跨境电商有限公司",
    contactName: "王总",
    phone: "138xxxx5678",
    interestedScenes: ["AI CEO 教练", "电商运营专家"],
    source: "官网留资",
    createdAt: "2026-03-27 14:32",
    status: "新线索",
    assignedToId: null,
    budgetLabel: "首期预算 ¥12-20 万",
    summary: "老板希望先从经营日报和销售跟进入手，最快 2 周内启动试点。",
    remark: "官网咨询后 15 分钟内回拨过，但仍需要补充试点门店数量。",
    progressList: [],
  },
  {
    id: "lead-02",
    companyName: "某制造企业",
    contactName: "张董",
    phone: "137xxxx2233",
    interestedScenes: ["供应链协同专家", "经营看板专家"],
    source: "FDE 服务页留资",
    createdAt: "2026-03-27 11:20",
    status: "新线索",
    assignedToId: null,
    budgetLabel: "首期预算 ¥8-15 万",
    summary: "关注多工厂排产建议和异常预警，希望先做供应链试点。",
    remark: "老板明确表示需要先看本地设备部署方式和安全方案。",
    progressList: [],
  },
  {
    id: "lead-03",
    companyName: "东岸家居品牌",
    contactName: "林薇",
    phone: "139xxxx1168",
    interestedScenes: ["内容创作专家", "商机洞察专家"],
    source: "老板转介绍",
    createdAt: "2026-03-26 18:04",
    status: "跟进中",
    assignedToId: "fde-engineer-luzhou",
    budgetLabel: "首期预算 ¥15-30 万",
    summary: "重点是基于 VOC 的新品决策和图文内容批量生产。",
    remark: "已经发了演示链接，下周三安排第二轮方案会。",
    progressList: [
      {
        id: "progress-03-01",
        content: "已发送产品演示链接，客户反馈对 VOC 分析功能很感兴趣。",
        createdAt: "2026-03-27 10:15",
        createdBy: "fde-engineer-luzhou",
      },
      {
        id: "progress-03-02",
        content: "约定下周三下午 2 点进行第二轮方案讨论，需要准备内容生产案例。",
        createdAt: "2026-03-28 16:30",
        createdBy: "fde-engineer-luzhou",
      },
    ],
  },
  {
    id: "lead-04",
    companyName: "百汇零售",
    contactName: "刘总",
    phone: "136xxxx9182",
    interestedScenes: ["经营看板专家", "财务对账专家", "招聘助手"],
    source: "官网留资",
    createdAt: "2026-03-22 09:10",
    status: "已成单",
    assignedToId: "fde-engineer-chenlan",
    budgetLabel: "签约金额 ¥49 万",
    summary: "已签首期 28 家门店试点，进入配置交付。",
    remark: "需要同步门店缺货、退货、招聘和经营简报。",
    progressList: [],
  },
  {
    id: "lead-05",
    companyName: "新锐科技",
    contactName: "赵慧",
    phone: "135xxxx1190",
    interestedScenes: ["AI CEO 教练", "招聘助手"],
    source: "线下活动",
    createdAt: "2026-03-19 17:45",
    status: "已成单",
    assignedToId: "fde-engineer-hejin",
    budgetLabel: "签约金额 ¥19.7 万",
    summary: "组织管理与招聘协同试点已确认签约。",
    remark: "需要本地设备 + 云端管理混合部署。",
    progressList: [],
  },
  {
    id: "lead-06",
    companyName: "南城服务集团",
    contactName: "杜斌",
    phone: "158xxxx8872",
    interestedScenes: ["客服质检官", "销售线索官"],
    source: "官网留资",
    createdAt: "2026-03-18 15:12",
    status: "已放弃",
    assignedToId: "fde-engineer-hejin",
    budgetLabel: "预算未明确",
    summary: "预算和组织优先级都没有确定，短期内不推进。",
    remark: "建议 60 天后再回访。",
    progressList: [],
  },
];

/**
 * FDE 配置交付工单。
 */
export const FDE_DELIVERY_ORDERS: FdeDeliveryOrderItem[] = [
  {
    id: "delivery-01",
    leadId: "lead-04",
    customerName: "卡尔顿",
    orderNo: "FDE-20260322-001",
    assignedToId: "fde-engineer-chenlan",
    industry: "企业服务",
    scenarioName: "AI CEO 教练",
    currentStep: "customerConfirm",
    stepProgress: 0,
    orderAmount: "¥19.6 万",
    deliveryNote: "客户要求五一之前必须上线。",
    deviceConfig: {
      mode: "混合部署",
      cloudDeviceCount: 2,
      localDeviceCount: 3,
      cloudNodeName: "",
      localDeviceName: "",
      pairingCode: "",
      osOwner: "LeDeep OS",
      region: "",
    },
    expertNames: ["AI CEO 教练"],
    apiTargets: [],
    memberCount: 0,
    createdAt: "2026-03-22 10:30",
    launchTargetDate: "2026-05-01",
    preflightChecks: ["设备完成配置", "Agent完成配置", "成员已经初始化"],
    completedSteps: [],
    deliveryStatus: "待配置",
  },
  {
    id: "delivery-02",
    leadId: "lead-05",
    customerName: "新锐科技",
    orderNo: "FDE-20260319-003",
    assignedToId: "fde-engineer-hejin",
    industry: "科技服务",
    scenarioName: "招聘协同 + 组织风险预警",
    currentStep: "deviceConfig",
    stepProgress: 26,
    orderAmount: "¥19.7 万",
    deliveryNote: "组织管理与招聘协同试点，需要本地设备 + 云端管理混合部署。优先对接 ATS 系统。",
    deviceConfig: {
      mode: "混合部署",
      cloudDeviceCount: 1,
      localDeviceCount: 1,
      cloudNodeName: "华南弹性节点 02",
      localDeviceName: "LeDeep Edge Mini",
      pairingCode: "待 OS 提供",
      osOwner: "LeDeep OS",
      region: "深圳",
    },
    expertNames: ["招聘助手", "组织风险雷达", "中层表现分析师"],
    apiTargets: ["ATS API", "企业微信通讯录", "绩效台账"],
    memberCount: 18,
    createdAt: "2026-03-20 09:00",
    launchTargetDate: "2026-04-12",
    preflightChecks: ["本地设备型号已锁定", "客户侧 API 权限申请中", "岗位地图已确认"],
    completedSteps: ["customerConfirm"],
    deliveryStatus: "配置中",
  },
];

/**
 * 运营监控客户。
 */
export const FDE_OPERATIONS_CUSTOMERS: FdeOperationsCustomerItem[] = [
  {
    id: "monitor-01",
    customerName: "百汇零售",
    scenarioName: "门店经营日清 + 财务对账",
    assignedToId: "fde-engineer-chenlan",
    health: "healthy",
    activeExperts: 4,
    onlineExperts: 4,
    issueCount: 1,
    messageVolume24h: 1268,
    taskCompletionRate: 96,
    lastHeartbeat: "2 分钟前",
    alertSummary: "招聘缺口预警 1 条，其余运行稳定。",
    highlights: ["晨报 7:58 自动生成", "28 家门店均已回流日报", "退货异常识别准确率 93%"],
    devices: [
      { id: "dev-01", name: "云端设备 1", type: "cloud", status: "online", uptime: "72小时" },
      { id: "dev-02", name: "云端设备 2", type: "cloud", status: "online", uptime: "72小时" },
      { id: "dev-03", name: "本地设备 1", type: "local", status: "online", uptime: "68小时" },
    ],
    agents: [
      { name: "经营收入师", runningHours: 72, completedTasks: 426 },
      { name: "对账核验师", runningHours: 72, completedTasks: 318 },
      { name: "补位协同师", runningHours: 68, completedTasks: 156 },
      { name: "晨报生成师", runningHours: 72, completedTasks: 28 },
    ],
    alerts: [],
  },
  {
    id: "monitor-02",
    customerName: "新锐科技",
    scenarioName: "招聘协同 + 组织风险预警",
    assignedToId: "fde-engineer-hejin",
    health: "attention",
    activeExperts: 3,
    onlineExperts: 3,
    issueCount: 2,
    messageVolume24h: 472,
    taskCompletionRate: 87,
    lastHeartbeat: "6 分钟前",
    alertSummary: "组织风险雷达缺一组部门权限，需要补配 API。",
    highlights: ["候选人筛选已跑通", "中层表现分析待接绩效数据", "设备心跳正常"],
    devices: [
      { id: "dev-04", name: "云端设备 1", type: "cloud", status: "offline", uptime: "0小时" },
      { id: "dev-05", name: "本地设备 1", type: "local", status: "online", uptime: "48小时" },
    ],
    agents: [
      { name: "招聘助手", runningHours: 48, completedTasks: 215 },
      { name: "组织风险雷达", runningHours: 48, completedTasks: 89 },
      { name: "中层表现分析师", runningHours: 32, completedTasks: 45 },
    ],
    alerts: [
      { id: "alert-01", message: "云端设备 1 显示掉线", severity: "high", time: "10 分钟前" },
    ],
  },
  {
    id: "monitor-03",
    customerName: "东岸家居品牌",
    scenarioName: "基于 VOC 的产品创新",
    assignedToId: "fde-engineer-luzhou",
    health: "risk",
    activeExperts: 4,
    onlineExperts: 3,
    issueCount: 4,
    messageVolume24h: 688,
    taskCompletionRate: 74,
    lastHeartbeat: "11 分钟前",
    alertSummary: "竞品爬取规则变更，VOC 评论流中断 2 小时。",
    highlights: ["评论采集恢复中", "图文产能仍可正常产出", "新品会建议待补全竞品数据"],
    devices: [
      { id: "dev-06", name: "云端设备 1", type: "cloud", status: "online", uptime: "120小时" },
      { id: "dev-07", name: "本地设备 1", type: "local", status: "online", uptime: "118小时" },
    ],
    agents: [
      { name: "AI CEO 教练", runningHours: 0, completedTasks: 0 },
      { name: "内容生产官", runningHours: 120, completedTasks: 502 },
      { name: "VOC 分析师", runningHours: 118, completedTasks: 234 },
      { name: "竞品监控官", runningHours: 96, completedTasks: 178 },
    ],
    alerts: [
      {
        id: "alert-02",
        message: "AI CEO 教练出现服务中断，判断是大模型问题",
        severity: "critical",
        time: "25 分钟前",
      },
    ],
  },
];

/**
 * 数据回流 Agent 指标。
 */
export const FDE_FEEDBACK_AGENTS: FdeFeedbackAgentItem[] = [
  {
    id: "feedback-01",
    agentName: "经营收入师",
    customerName: "百汇零售",
    customerId: "monitor-01",
    assignedToId: "fde-engineer-chenlan",
    scenarioName: "门店经营日清 + 财务对账",
    resolutionRate: 96,
    triggerCount: 426,
    evolutionScore: 78,
    lastEvolvedAt: "2026-03-20",
    currentVersion: "v1.7.2",
    skills: [
      { name: "营收汇总", version: "v1.2.0" },
      { name: "退货识别", version: "v1.1.5" },
      { name: "缺货归因", version: "v1.0.8" },
    ],
    feedbackData: [
      { date: "2026-03-22", triggerCount: 68, successCount: 65, failCount: 3, avgResponseTime: 1.2 },
      { date: "2026-03-23", triggerCount: 72, successCount: 69, failCount: 3, avgResponseTime: 1.1 },
      { date: "2026-03-24", triggerCount: 65, successCount: 63, failCount: 2, avgResponseTime: 1.3 },
      { date: "2026-03-25", triggerCount: 70, successCount: 68, failCount: 2, avgResponseTime: 1.2 },
      { date: "2026-03-26", triggerCount: 75, successCount: 72, failCount: 3, avgResponseTime: 1.1 },
      { date: "2026-03-27", triggerCount: 76, successCount: 73, failCount: 3, avgResponseTime: 1.2 },
    ],
  },
  {
    id: "feedback-02",
    agentName: "对账核验师",
    customerName: "百汇零售",
    customerId: "monitor-01",
    assignedToId: "fde-engineer-chenlan",
    scenarioName: "门店经营日清 + 财务对账",
    resolutionRate: 92,
    triggerCount: 318,
    evolutionScore: 84,
    lastEvolvedAt: "2026-03-18",
    currentVersion: "v1.5.3",
    skills: [
      { name: "流水核对", version: "v1.3.0" },
      { name: "退款异常", version: "v1.2.1" },
      { name: "周均对比", version: "v1.1.0" },
    ],
    feedbackData: [
      { date: "2026-03-22", triggerCount: 52, successCount: 48, failCount: 4, avgResponseTime: 2.1 },
      { date: "2026-03-23", triggerCount: 54, successCount: 50, failCount: 4, avgResponseTime: 2.0 },
      { date: "2026-03-24", triggerCount: 50, successCount: 46, failCount: 4, avgResponseTime: 2.2 },
      { date: "2026-03-25", triggerCount: 53, successCount: 49, failCount: 4, avgResponseTime: 2.1 },
      { date: "2026-03-26", triggerCount: 55, successCount: 51, failCount: 4, avgResponseTime: 2.0 },
      { date: "2026-03-27", triggerCount: 54, successCount: 50, failCount: 4, avgResponseTime: 2.1 },
    ],
  },
  {
    id: "feedback-03",
    agentName: "招聘助手",
    customerName: "新锐科技",
    customerId: "monitor-02",
    assignedToId: "fde-engineer-hejin",
    scenarioName: "招聘协同 + 组织风险预警",
    resolutionRate: 88,
    triggerCount: 215,
    evolutionScore: 69,
    lastEvolvedAt: "2026-03-15",
    currentVersion: "v2.3.1",
    skills: [
      { name: "简历筛选", version: "v2.1.0" },
      { name: "JD 拆写", version: "v1.8.2" },
      { name: "面试问题生成", version: "v1.5.0" },
    ],
    feedbackData: [
      { date: "2026-03-22", triggerCount: 35, successCount: 31, failCount: 4, avgResponseTime: 3.2 },
      { date: "2026-03-23", triggerCount: 38, successCount: 33, failCount: 5, avgResponseTime: 3.1 },
      { date: "2026-03-24", triggerCount: 32, successCount: 28, failCount: 4, avgResponseTime: 3.3 },
      { date: "2026-03-25", triggerCount: 36, successCount: 32, failCount: 4, avgResponseTime: 3.2 },
      { date: "2026-03-26", triggerCount: 37, successCount: 33, failCount: 4, avgResponseTime: 3.1 },
      { date: "2026-03-27", triggerCount: 37, successCount: 32, failCount: 5, avgResponseTime: 3.2 },
    ],
  },
  {
    id: "feedback-04",
    agentName: "内容生产官",
    customerName: "东岸家居品牌",
    customerId: "monitor-03",
    assignedToId: "fde-engineer-luzhou",
    scenarioName: "基于 VOC 的产品创新",
    resolutionRate: 85,
    triggerCount: 502,
    evolutionScore: 73,
    lastEvolvedAt: "2026-03-12",
    currentVersion: "v3.7.4",
    skills: [
      { name: "商品主图生成", version: "v3.2.0" },
      { name: "商品图合成", version: "v2.8.1" },
      { name: "风格迁移", version: "v2.5.0" },
    ],
    feedbackData: [
      { date: "2026-03-22", triggerCount: 82, successCount: 70, failCount: 12, avgResponseTime: 4.5 },
      { date: "2026-03-23", triggerCount: 85, successCount: 72, failCount: 13, avgResponseTime: 4.6 },
      { date: "2026-03-24", triggerCount: 80, successCount: 68, failCount: 12, avgResponseTime: 4.4 },
      { date: "2026-03-25", triggerCount: 84, successCount: 71, failCount: 13, avgResponseTime: 4.5 },
      { date: "2026-03-26", triggerCount: 86, successCount: 73, failCount: 13, avgResponseTime: 4.6 },
      { date: "2026-03-27", triggerCount: 85, successCount: 72, failCount: 13, avgResponseTime: 4.5 },
    ],
  },
];

/**
 * 进化任务。
 */
export const FDE_EVOLUTION_TASKS: FdeEvolutionTaskItem[] = [
  {
    id: "evo-01",
    agentName: "内容生产官",
    customerName: "东岸家居品牌",
    assignedToId: "fde-engineer-luzhou",
    status: "进化中",
    progress: 62,
    versionCandidate: "v3.8.0",
    source: "手动触发",
    startedAt: "2026-03-27 10:40",
    expectedFinishAt: "2026-03-28 19:00",
    changedSkills: ["商品图合成", "风格一致性", "模板检索"],
    summary: "基于 280 张新品图和 64 条 VOC 评论，提升新品会前图文产能。",
    estimatedTime: "约 8 小时",
  },
  {
    id: "evo-02",
    agentName: "招聘助手",
    customerName: "新锐科技",
    assignedToId: "fde-engineer-hejin",
    status: "进化已完成",
    progress: 100,
    versionCandidate: "v2.4.0",
    source: "自动回流",
    startedAt: "2026-03-26 09:00",
    expectedFinishAt: "2026-03-27 16:00",
    changedSkills: ["技术岗匹配", "候选人优先级排序"],
    summary: "完成 50 份录用案例回灌，技能进化已完成。",
    benchmarkResults: [
      {
        skillName: "技术岗匹配",
        oldVersion: "v2.1.0",
        newVersion: "v2.2.0",
        metrics: [
          { name: "会议录音准确率", oldValue: "74%", newValue: "91%", improvement: "↑ +23%" },
          { name: "周报生成耗时", oldValue: "4.2min", newValue: "1.1min", improvement: "↓ -74%" },
          { name: "异常检测召回率", oldValue: "68%", newValue: "79%", improvement: "↑ +16%" },
          { name: "错误率", oldValue: "3.2%", newValue: "2.1%", improvement: "↓ -34%" },
        ],
      },
      {
        skillName: "候选人优先级排序",
        oldVersion: "v1.8.2",
        newVersion: "v1.9.0",
        metrics: [
          { name: "排序准确率", oldValue: "76%", newValue: "84%", improvement: "↑ +11%" },
          { name: "响应时间", oldValue: "2.1s", newValue: "1.9s", improvement: "↓ -10%" },
        ],
      },
    ],
  },
  {
    id: "evo-03",
    agentName: "对账核验师",
    customerName: "百汇零售",
    assignedToId: "fde-engineer-chenlan",
    status: "排队中",
    progress: 0,
    versionCandidate: "v1.9.0",
    source: "手动触发",
    startedAt: "2026-03-28 09:30",
    expectedFinishAt: "2026-03-29 14:00",
    changedSkills: ["节假日退款阈值", "门店聚合速度"],
    summary: "补入周末退款异常样本，准备提升核验准确率与响应速度。",
    queuePosition: 2,
  },
  {
    id: "evo-04",
    agentName: "经营收入师",
    customerName: "百汇零售",
    assignedToId: "fde-engineer-chenlan",
    status: "已推送客户审核中",
    progress: 100,
    versionCandidate: "v1.8.0",
    source: "自动回流",
    startedAt: "2026-03-24 14:20",
    expectedFinishAt: "2026-03-25 18:00",
    changedSkills: ["营收汇总", "退货识别"],
    summary: "优化门店营收汇总逻辑，提升退货异常识别准确率。",
    upgradeNotes: "本次升级主要优化了门店营收汇总的计算逻辑，修复了节假日退货识别的误判问题。建议客户在非高峰期进行升级测试。",
    currentVersion: "v1.7.2",
  },
  {
    id: "evo-05",
    agentName: "VOC 分析师",
    customerName: "东岸家居品牌",
    assignedToId: "fde-engineer-luzhou",
    status: "客户已采纳",
    progress: 100,
    versionCandidate: "v2.5.0",
    source: "手动触发",
    startedAt: "2026-03-20 10:00",
    expectedFinishAt: "2026-03-21 16:00",
    changedSkills: ["评论情感分析", "竞品对比"],
    summary: "增强评论情感分析能力，新增竞品对比维度。",
    currentVersion: "v2.5.0",
    upgradeNotes: "客户已于 2026-03-26 采纳并部署到生产环境，运行稳定。",
  },
  {
    id: "evo-06",
    agentName: "补位协同师",
    customerName: "百汇零售",
    assignedToId: "fde-engineer-chenlan",
    status: "客户未采纳",
    progress: 100,
    versionCandidate: "v1.3.0",
    source: "自动回流",
    startedAt: "2026-03-18 09:00",
    expectedFinishAt: "2026-03-19 15:00",
    changedSkills: ["缺货预警", "补货建议"],
    summary: "优化缺货预警算法，增加智能补货建议。",
    rejectionReason: "客户反馈补货建议与实际业务流程不符，需要重新调整算法逻辑后再提交。",
  },
];

/**
 * 默认线索表单。
 */
export const createInitialFdeLeadFormState = (): FdeLeadFormState => ({
  companyName: "",
  contactName: "",
  phone: "",
  interestedScenes: [],
  source: "官网留资",
  budgetLabel: "",
  summary: "",
  remark: "",
  assignedToId: null,
});
