import type {
  FdeDeliveryOrderItem,
  FdeDeliveryStepItem,
  FdeEvolutionTaskItem,
  FdeFeedbackAgentItem,
  FdeLeadFormState,
  FdeLeadItem,
  FdeOperationsCustomerItem,
  FdeOpportunityItem,
  FdeReleasePushItem,
  FdeTeamMemberItem,
  FdeTimelineItem,
  FdeWorkbenchTabItem,
} from "@/feature/fde/types";

const buildTimelineItem = (
  id: string,
  title: string,
  detail: string,
  createdAt: string,
): FdeTimelineItem => ({
  id,
  title,
  detail,
  createdAt,
});

/**
 * FDE 工作台导航。
 */
export const FDE_WORKBENCH_TABS: FdeWorkbenchTabItem[] = [
  { key: "overview", label: "工作台总览", description: "待办中心、统一日志与跨模块检索" },
  { key: "opportunities", label: "商机工作台", description: "团队商机与转化漏斗" },
  { key: "leads", label: "线索工单", description: "线索录入、分配与状态流转" },
  { key: "delivery", label: "配置交付", description: "正式订单交付与专家团配置" },
  { key: "operations", label: "运营监控", description: "客户 AI 专家团实时运行状态" },
  { key: "feedback", label: "数据回流看板", description: "按 Agent 查看回流数据与进化建议" },
  { key: "evolution", label: "进化任务管理", description: "训练中与待审核的进化任务" },
  { key: "releases", label: "版本推送", description: "升级后的 Agent 推送记录" },
];

/**
 * FDE 交付步骤。
 */
export const FDE_DELIVERY_STEPS: FdeDeliveryStepItem[] = [
  { key: "customerConfirm", label: "客户信息确认" },
  { key: "deviceConfig", label: "设备配置" },
  { key: "agentConfig", label: "Agent配置" },
  { key: "apiTest", label: "API测试" },
  { key: "memberInit", label: "成员初始化" },
  { key: "preflight", label: "发货前检查" },
];

/**
 * FDE 团队成员。
 */
export const FDE_TEAM_MEMBERS: FdeTeamMemberItem[] = [
  {
    id: "fde-leader-wanglin",
    name: "王琳",
    title: "FDE 团队负责人",
    role: "leader",
    status: "online",
    focusScenes: ["商机诊断", "交付策略", "版本审核"],
    avatarSeed: "wang-lin",
  },
  {
    id: "fde-engineer-chenlan",
    name: "陈岚",
    title: "资深交付工程师",
    role: "engineer",
    status: "online",
    focusScenes: ["经营管理", "销售增长", "数据回流"],
    avatarSeed: "chen-lan",
  },
  {
    id: "fde-engineer-luzhou",
    name: "陆舟",
    title: "FDE 配置工程师",
    role: "engineer",
    status: "busy",
    focusScenes: ["内容创作", "本地设备部署", "版本灰度"],
    avatarSeed: "lu-zhou",
  },
  {
    id: "fde-engineer-hejin",
    name: "何晋",
    title: "FDE 运营工程师",
    role: "engineer",
    status: "online",
    focusScenes: ["客户服务", "线索工单", "运营监控"],
    avatarSeed: "he-jin",
  },
];

/**
 * FDE 商机数据。
 */
export const FDE_OPPORTUNITIES: FdeOpportunityItem[] = [
  {
    id: "opp-01",
    sourceLeadId: null,
    companyName: "智联制造",
    contactName: "周总",
    contactPhone: "139xxxx7821",
    scenarioName: "经营日报 + 门店动作同步",
    industry: "制造零售",
    stage: "初步沟通",
    amountWan: 18.8,
    winRate: 32,
    ownerId: "fde-engineer-chenlan",
    priority: "中",
    riskLevel: "关注",
    budgetLabel: "首期预算 ¥12-20 万",
    nextAction: "安排老板演示经营日报链路",
    nextActionDate: "2026-03-31",
    estimatedSignDate: "2026-04-18",
    source: "官网咨询",
    summary: "对门店日报、排班和缺货风险特别关注。",
    blockers: ["需先确认试点门店数量"],
    timeline: [
      buildTimelineItem(
        "opp-01-log-01",
        "商机入池",
        "官网咨询后进入 FDE 商机池，待安排首轮业务沟通。",
        "2026-03-28 09:20",
      ),
      buildTimelineItem(
        "opp-01-log-02",
        "确认演示重点",
        "已锁定经营日报、排班同步和缺货预警作为首轮演示内容。",
        "2026-03-29 10:40",
      ),
    ],
  },
  {
    id: "opp-02",
    sourceLeadId: null,
    companyName: "环球电商",
    contactName: "林总",
    contactPhone: "137xxxx6218",
    scenarioName: "基于 VOC 的产品创新",
    industry: "跨境电商",
    stage: "产品演示",
    amountWan: 26.5,
    winRate: 52,
    ownerId: "fde-engineer-luzhou",
    priority: "高",
    riskLevel: "关注",
    budgetLabel: "首期预算 ¥20-30 万",
    nextAction: "补演 VOC 看板和产品创新节奏",
    nextActionDate: "2026-04-02",
    estimatedSignDate: "2026-04-20",
    source: "FDE 服务页",
    summary: "老板希望先用评论和竞品动态跑通新品会决策。",
    blockers: ["竞品评论数据接入方案待确认"],
    timeline: [
      buildTimelineItem(
        "opp-02-log-01",
        "服务页留资转商机",
        "客户通过 FDE 服务页留资，明确提出 VOC 与新品会需求。",
        "2026-03-24 14:10",
      ),
      buildTimelineItem(
        "opp-02-log-02",
        "完成首轮演示",
        "已展示 VOC 聚类与新品会建议链路，等待补充竞品数据方案。",
        "2026-03-28 16:30",
      ),
    ],
  },
  {
    id: "opp-03",
    sourceLeadId: null,
    companyName: "创新医疗",
    contactName: "赵院长",
    contactPhone: "136xxxx5508",
    scenarioName: "销售线索分层 + 战报推送",
    industry: "医疗服务",
    stage: "方案推荐",
    amountWan: 34.2,
    winRate: 63,
    ownerId: "fde-engineer-chenlan",
    priority: "高",
    riskLevel: "低风险",
    budgetLabel: "首期预算 ¥30-40 万",
    nextAction: "输出正式方案和设备部署说明",
    nextActionDate: "2026-03-30",
    estimatedSignDate: "2026-04-10",
    source: "老板转介绍",
    summary: "重点看多院区销售协同和一线跟进质检。",
    blockers: [],
    timeline: [
      buildTimelineItem(
        "opp-03-log-01",
        "转介绍商机入池",
        "老板转介绍后快速完成一轮需求澄清，意向较明确。",
        "2026-03-22 11:00",
      ),
      buildTimelineItem(
        "opp-03-log-02",
        "输出方案框架",
        "已形成多院区销售协同与战报推送方案框架，待设备说明。",
        "2026-03-29 09:10",
      ),
    ],
  },
  {
    id: "opp-04",
    sourceLeadId: "lead-05",
    companyName: "新锐科技",
    contactName: "赵慧",
    contactPhone: "135xxxx1190",
    scenarioName: "招聘协同 + 组织风险预警",
    industry: "科技服务",
    stage: "商务谈判",
    amountWan: 19.7,
    winRate: 84,
    ownerId: "fde-engineer-hejin",
    priority: "高",
    riskLevel: "低风险",
    budgetLabel: "签约金额 ¥19.7 万",
    nextAction: "确认采购清单与本地设备数量",
    nextActionDate: "2026-03-29",
    estimatedSignDate: "2026-03-30",
    source: "线下活动",
    summary: "已确认试点部门和 PO，进入商务条款确认。",
    blockers: ["本地设备数量待老板最终拍板"],
    timeline: [
      buildTimelineItem(
        "opp-04-log-01",
        "线索转商机",
        "线下活动线索完成首轮沟通后，进入商机推进阶段。",
        "2026-03-20 13:20",
      ),
      buildTimelineItem(
        "opp-04-log-02",
        "进入商务谈判",
        "采购清单和试点范围已确认，待敲定本地设备数量。",
        "2026-03-28 18:00",
      ),
    ],
  },
  {
    id: "opp-05",
    sourceLeadId: "lead-04",
    companyName: "百汇零售",
    contactName: "刘总",
    contactPhone: "136xxxx9182",
    scenarioName: "门店经营日清 + 财务对账",
    industry: "零售连锁",
    stage: "已成交",
    amountWan: 49.0,
    winRate: 100,
    ownerId: "fde-engineer-chenlan",
    priority: "高",
    riskLevel: "低风险",
    budgetLabel: "签约金额 ¥49 万",
    nextAction: "进入配置交付与设备发货",
    nextActionDate: "2026-03-28",
    estimatedSignDate: "2026-03-28",
    source: "官网咨询",
    summary: "签约首期 28 家门店，FDE 已进入设备配置阶段。",
    blockers: [],
    timeline: [
      buildTimelineItem(
        "opp-05-log-01",
        "线索转商机",
        "官网留资后完成多轮演示与预算确认，进入商机阶段。",
        "2026-03-23 10:00",
      ),
      buildTimelineItem(
        "opp-05-log-02",
        "确认签约",
        "首期 28 家门店试点完成签约，转交配置交付。",
        "2026-03-28 15:20",
      ),
    ],
  },
  {
    id: "opp-06",
    sourceLeadId: null,
    companyName: "极客供应链",
    contactName: "韩总",
    contactPhone: "138xxxx4021",
    scenarioName: "供应链异常预警 + 补位建议",
    industry: "供应链",
    stage: "产品演示",
    amountWan: 22.4,
    winRate: 45,
    ownerId: "fde-engineer-hejin",
    priority: "中",
    riskLevel: "关注",
    budgetLabel: "首期预算 ¥15-25 万",
    nextAction: "安排对接 ERP 与库存 API",
    nextActionDate: "2026-04-01",
    estimatedSignDate: "2026-04-15",
    source: "FDE 服务页",
    summary: "需要把采购、库存和交付预警汇成一套 AI 协作流。",
    blockers: ["ERP 接口字段说明尚未提供"],
    timeline: [
      buildTimelineItem(
        "opp-06-log-01",
        "商机创建",
        "FDE 服务页留资后已确认供应链异常预警是核心试点方向。",
        "2026-03-25 17:30",
      ),
      buildTimelineItem(
        "opp-06-log-02",
        "等待接口材料",
        "客户侧正在整理 ERP 与库存 API 字段说明文档。",
        "2026-03-29 11:15",
      ),
    ],
  },
];

/**
 * FDE 线索工单数据。
 */
export const FDE_LEADS: FdeLeadItem[] = [
  {
    id: "lead-01",
    companyName: "某跨境电商有限公司",
    contactName: "王总",
    phone: "138xxxx5678",
    interestedScenes: ["AI CEO 教练", "电商运营专家"],
    source: "官网留资",
    createdAt: "2026-03-27 14:32",
    status: "新线索",
    assignedToId: "fde-engineer-chenlan",
    priority: "高",
    budgetLabel: "首期预算 ¥12-20 万",
    nextFollowUpAt: "2026-03-30 10:00",
    lastFollowUpAt: "2026-03-27 14:50",
    summary: "老板希望先从经营日报和销售跟进入手，最快 2 周内启动试点。",
    remark: "官网咨询后 15 分钟内回拨过，但仍需要补充试点门店数量。",
    timeline: [
      buildTimelineItem(
        "lead-01-log-01",
        "线索创建",
        "官网留资后进入线索池，等待 FDE 跟进。",
        "2026-03-27 14:32",
      ),
      buildTimelineItem(
        "lead-01-log-02",
        "完成首轮回拨",
        "已回拨确认老板关注经营日报和销售跟进场景。",
        "2026-03-27 14:50",
      ),
    ],
  },
  {
    id: "lead-02",
    companyName: "某制造企业",
    contactName: "张董",
    phone: "137xxxx2233",
    interestedScenes: ["供应链协同专家", "经营看板专家"],
    source: "FDE 服务页留资",
    createdAt: "2026-03-27 11:20",
    status: "新线索",
    assignedToId: "fde-engineer-hejin",
    priority: "中",
    budgetLabel: "首期预算 ¥8-15 万",
    nextFollowUpAt: "2026-03-29 16:00",
    lastFollowUpAt: "2026-03-27 16:40",
    summary: "关注多工厂排产建议和异常预警，希望先做供应链试点。",
    remark: "老板明确表示需要先看本地设备部署方式和安全方案。",
    timeline: [
      buildTimelineItem(
        "lead-02-log-01",
        "线索创建",
        "FDE 服务页留资后自动进入线索工单。",
        "2026-03-27 11:20",
      ),
      buildTimelineItem(
        "lead-02-log-02",
        "补充关注点",
        "已确认客户重点关注本地设备部署方式与安全方案。",
        "2026-03-27 16:40",
      ),
    ],
  },
  {
    id: "lead-03",
    companyName: "东岸家居品牌",
    contactName: "林薇",
    phone: "139xxxx1168",
    interestedScenes: ["内容创作专家", "商机洞察专家"],
    source: "老板转介绍",
    createdAt: "2026-03-26 18:04",
    status: "跟进中",
    assignedToId: "fde-engineer-luzhou",
    priority: "高",
    budgetLabel: "首期预算 ¥15-30 万",
    nextFollowUpAt: "2026-03-31 15:00",
    lastFollowUpAt: "2026-03-28 11:20",
    summary: "重点是基于 VOC 的新品决策和图文内容批量生产。",
    remark: "已经发了演示链接，下周三安排第二轮方案会。",
    timeline: [
      buildTimelineItem(
        "lead-03-log-01",
        "线索创建",
        "通过老板转介绍进入 FDE 线索池。",
        "2026-03-26 18:04",
      ),
      buildTimelineItem(
        "lead-03-log-02",
        "发送演示资料",
        "已发送演示链接并约定下周三进行第二轮方案会。",
        "2026-03-28 11:20",
      ),
    ],
  },
  {
    id: "lead-04",
    companyName: "百汇零售",
    contactName: "刘总",
    phone: "136xxxx9182",
    interestedScenes: ["经营看板专家", "财务对账专家", "招聘助手"],
    source: "官网留资",
    createdAt: "2026-03-22 09:10",
    status: "已转商机",
    assignedToId: "fde-engineer-chenlan",
    priority: "高",
    budgetLabel: "签约金额 ¥49 万",
    nextFollowUpAt: "",
    lastFollowUpAt: "2026-03-23 10:00",
    summary: "已签首期 28 家门店试点，进入配置交付。",
    remark: "需要同步门店缺货、退货、招聘和经营简报。",
    timeline: [
      buildTimelineItem(
        "lead-04-log-01",
        "线索创建",
        "官网留资后快速完成业务澄清并进入重点跟进。",
        "2026-03-22 09:10",
      ),
      buildTimelineItem(
        "lead-04-log-02",
        "已转入商机",
        "已转商机推进并完成签约，当前进入配置交付阶段。",
        "2026-03-23 10:00",
      ),
    ],
  },
  {
    id: "lead-05",
    companyName: "新锐科技",
    contactName: "赵慧",
    phone: "135xxxx1190",
    interestedScenes: ["AI CEO 教练", "招聘助手"],
    source: "线下活动",
    createdAt: "2026-03-19 17:45",
    status: "已转商机",
    assignedToId: "fde-engineer-hejin",
    priority: "高",
    budgetLabel: "签约金额 ¥19.7 万",
    nextFollowUpAt: "",
    lastFollowUpAt: "2026-03-20 13:20",
    summary: "组织管理与招聘协同试点已确认签约。",
    remark: "需要本地设备 + 云端管理混合部署。",
    timeline: [
      buildTimelineItem(
        "lead-05-log-01",
        "线索创建",
        "线下活动交换名片后录入系统，聚焦招聘与组织协同场景。",
        "2026-03-19 17:45",
      ),
      buildTimelineItem(
        "lead-05-log-02",
        "已转入商机",
        "确认试点部门与预算后转入商机工作台持续推进。",
        "2026-03-20 13:20",
      ),
    ],
  },
  {
    id: "lead-06",
    companyName: "南城服务集团",
    contactName: "杜斌",
    phone: "158xxxx8872",
    interestedScenes: ["客服质检官", "销售线索官"],
    source: "官网留资",
    createdAt: "2026-03-18 15:12",
    status: "已放弃",
    assignedToId: "fde-engineer-hejin",
    priority: "低",
    budgetLabel: "预算未明确",
    nextFollowUpAt: "2026-05-18 10:00",
    lastFollowUpAt: "2026-03-19 10:30",
    summary: "预算和组织优先级都没有确定，短期内不推进。",
    remark: "建议 60 天后再回访。",
    timeline: [
      buildTimelineItem(
        "lead-06-log-01",
        "线索创建",
        "官网留资后进入线索池，等待首轮需求确认。",
        "2026-03-18 15:12",
      ),
      buildTimelineItem(
        "lead-06-log-02",
        "标记暂缓",
        "预算与组织优先级未明确，建议 60 天后再回访。",
        "2026-03-19 10:30",
      ),
    ],
  },
];

/**
 * FDE 配置交付工单。
 */
export const FDE_DELIVERY_ORDERS: FdeDeliveryOrderItem[] = [
  {
    id: "delivery-01",
    leadId: "lead-04",
    sourceOpportunityId: "opp-05",
    customerName: "百汇零售",
    orderNo: "FDE-20260322-001",
    assignedToId: "fde-engineer-chenlan",
    industry: "零售连锁",
    scenarioName: "门店经营日清 + 财务对账",
    currentStep: "agentConfig",
    stepProgress: 48,
    deviceConfig: {
      mode: "本地设备",
      cloudNodeName: "华东云边节点 03",
      localDeviceName: "LeDeep Box Pro × 3",
      pairingCode: "OS-84DK-2P1R",
      osOwner: "LeDeep OS",
      region: "上海 / 苏州",
    },
    expertNames: ["经营收入师", "对账核验师", "补位协同师", "晨报生成师"],
    apiTargets: ["ERP 订单接口", "门店排班接口", "招聘系统 API"],
    apiIntegrations: [
      {
        id: "delivery-01-api-01",
        name: "ERP 订单接口",
        note: "订单与退货流水已完成双向联调。",
        status: "已完成",
      },
      {
        id: "delivery-01-api-02",
        name: "门店排班接口",
        note: "排班变更回流仍需补店长审批字段。",
        status: "联调中",
      },
      {
        id: "delivery-01-api-03",
        name: "招聘系统 API",
        note: "等待客户开放白名单。",
        status: "待联调",
      },
    ],
    memberCount: 36,
    memberInit: {
      targetCount: 36,
      activatedCount: 28,
      trainingCompletedCount: 20,
      summary: "首批门店店长和财务主管已完成账号开通，等待剩余岗位培训。",
    },
    blockers: [
      {
        id: "delivery-01-blocker-01",
        title: "门店排班接口字段缺失",
        detail: "门店排班接口缺少店长审批字段，影响交班提醒联动。",
        dueDate: "2026-03-31",
        ownerId: "fde-engineer-chenlan",
        status: "处理中",
      },
    ],
    createdAt: "2026-03-22 10:30",
    launchTargetDate: "2026-04-08",
    preflightChecks: ["设备序列号已确认", "接口白名单待最终核验", "门店成员名单已收齐"],
    acceptance: {
      status: "待验收",
      acceptedAt: "",
      handoverOwner: "王琳",
      summary: "待完成接口白名单与全员培训后进入客户上线验收。",
      checklist: ["晨报自动生成核验", "门店日报回流抽检", "老板端经营看板演示通过"],
    },
  },
  {
    id: "delivery-02",
    leadId: "lead-05",
    sourceOpportunityId: "opp-04",
    customerName: "新锐科技",
    orderNo: "FDE-20260319-003",
    assignedToId: "fde-engineer-hejin",
    industry: "科技服务",
    scenarioName: "招聘协同 + 组织风险预警",
    currentStep: "deviceConfig",
    stepProgress: 26,
    deviceConfig: {
      mode: "混合部署",
      cloudNodeName: "华南弹性节点 02",
      localDeviceName: "LeDeep Edge Mini × 1",
      pairingCode: "待 OS 提供",
      osOwner: "LeDeep OS",
      region: "深圳",
    },
    expertNames: ["招聘助手", "组织风险雷达", "中层表现分析师"],
    apiTargets: ["ATS API", "企业微信通讯录", "绩效台账"],
    apiIntegrations: [
      {
        id: "delivery-02-api-01",
        name: "ATS API",
        note: "候选人状态同步已打通，待补面试评价字段。",
        status: "联调中",
      },
      {
        id: "delivery-02-api-02",
        name: "企业微信通讯录",
        note: "企业微信组织架构同步已完成。",
        status: "已完成",
      },
      {
        id: "delivery-02-api-03",
        name: "绩效台账",
        note: "绩效台账接口仍在申请读取权限。",
        status: "待联调",
      },
    ],
    memberCount: 18,
    memberInit: {
      targetCount: 18,
      activatedCount: 9,
      trainingCompletedCount: 5,
      summary: "招聘部门已完成首批启用，组织预警相关角色仍在补权限。",
    },
    blockers: [
      {
        id: "delivery-02-blocker-01",
        title: "绩效台账权限未开通",
        detail: "绩效台账接口还未通过客户侧安全审批，影响组织风险雷达上线。",
        dueDate: "2026-04-01",
        ownerId: "fde-engineer-hejin",
        status: "待处理",
      },
    ],
    createdAt: "2026-03-20 09:00",
    launchTargetDate: "2026-04-12",
    preflightChecks: ["本地设备型号已锁定", "客户侧 API 权限申请中", "岗位地图已确认"],
    acceptance: {
      status: "待验收",
      acceptedAt: "",
      handoverOwner: "王琳",
      summary: "待绩效台账联调完成后，安排组织风险预警专项验收。",
      checklist: ["招聘助手联调通过", "组织权限映射核对", "老板演示场景排练完成"],
    },
  },
];

/**
 * 运营监控客户。
 */
export const FDE_OPERATIONS_CUSTOMERS: FdeOperationsCustomerItem[] = [
  {
    id: "monitor-01",
    customerName: "百汇零售",
    scenarioName: "门店经营日清 + 财务对账",
    assignedToId: "fde-engineer-chenlan",
    health: "healthy",
    activeExperts: 4,
    onlineExperts: 4,
    issueCount: 1,
    messageVolume24h: 1268,
    taskCompletionRate: 96,
    lastHeartbeat: "2 分钟前",
    alertSummary: "招聘缺口预警 1 条，其余运行稳定。",
    highlights: ["晨报 7:58 自动生成", "28 家门店均已回流日报", "退货异常识别准确率 93%"],
    alerts: [
      {
        id: "monitor-01-alert-01",
        title: "招聘缺口预警触发延迟",
        detail: "门店招聘缺口预警在夜班切换后延迟 12 分钟触发。",
        sourceType: "专家",
        sourceName: "补位协同师",
        severity: "中",
        status: "处理中",
        ownerId: "fde-engineer-chenlan",
        createdAt: "2026-03-29 08:16",
        resolution: "已定位为夜班门店回流延迟，等待门店排班接口修复。",
      },
    ],
    agentDiagnostics: [
      {
        id: "monitor-01-agent-01",
        name: "经营收入师",
        note: "日报汇总稳定，近 24h 未出现异常。",
        status: "正常",
      },
      {
        id: "monitor-01-agent-02",
        name: "补位协同师",
        note: "招聘缺口预警存在夜班触发延迟。",
        status: "关注",
      },
    ],
    apiDiagnostics: [
      {
        id: "monitor-01-api-01",
        name: "ERP 订单接口",
        note: "订单回流稳定，近 24h 成功率 99.6%。",
        status: "正常",
      },
      {
        id: "monitor-01-api-02",
        name: "门店排班接口",
        note: "夜班门店排班字段存在延迟，影响招聘提醒。",
        status: "关注",
      },
    ],
    deviceDiagnostics: [
      {
        id: "monitor-01-device-01",
        name: "LeDeep Box Pro × 3",
        note: "三台设备心跳正常，离线风险低。",
        status: "正常",
      },
      {
        id: "monitor-01-device-02",
        name: "华东云边节点 03",
        note: "节点负载平稳，无扩容风险。",
        status: "正常",
      },
    ],
    trends: [
      { label: "03-25", alertCount: 2, completionRate: 94, messageVolume: 1180, onlineRate: 100 },
      { label: "03-26", alertCount: 1, completionRate: 95, messageVolume: 1208, onlineRate: 100 },
      { label: "03-27", alertCount: 1, completionRate: 95, messageVolume: 1236, onlineRate: 100 },
      { label: "03-28", alertCount: 2, completionRate: 96, messageVolume: 1254, onlineRate: 100 },
      { label: "03-29", alertCount: 1, completionRate: 96, messageVolume: 1268, onlineRate: 100 },
    ],
  },
  {
    id: "monitor-02",
    customerName: "新锐科技",
    scenarioName: "招聘协同 + 组织风险预警",
    assignedToId: "fde-engineer-hejin",
    health: "attention",
    activeExperts: 3,
    onlineExperts: 3,
    issueCount: 2,
    messageVolume24h: 472,
    taskCompletionRate: 87,
    lastHeartbeat: "6 分钟前",
    alertSummary: "组织风险雷达缺一组部门权限，需要补配 API。",
    highlights: ["候选人筛选已跑通", "中层表现分析待接绩效数据", "设备心跳正常"],
    alerts: [
      {
        id: "monitor-02-alert-01",
        title: "绩效台账权限未开通",
        detail: "组织风险雷达缺少绩效台账读取权限，导致风险分层不完整。",
        sourceType: "接口",
        sourceName: "绩效台账",
        severity: "高",
        status: "待确认",
        ownerId: "fde-engineer-hejin",
        createdAt: "2026-03-29 09:40",
        resolution: "",
      },
      {
        id: "monitor-02-alert-02",
        title: "组织架构同步延迟",
        detail: "企业微信组织架构在 08:00 后同步出现 7 分钟延迟。",
        sourceType: "设备",
        sourceName: "华南弹性节点 02",
        severity: "中",
        status: "处理中",
        ownerId: "fde-engineer-hejin",
        createdAt: "2026-03-29 10:10",
        resolution: "已观察到云端节点瞬时负载偏高，正在调整同步窗口。",
      },
    ],
    agentDiagnostics: [
      {
        id: "monitor-02-agent-01",
        name: "招聘助手",
        note: "筛选流程稳定，但绩效标签仍不完整。",
        status: "关注",
      },
      {
        id: "monitor-02-agent-02",
        name: "组织风险雷达",
        note: "因绩效台账权限缺失，风险画像无法完整输出。",
        status: "异常",
      },
    ],
    apiDiagnostics: [
      {
        id: "monitor-02-api-01",
        name: "ATS API",
        note: "联调完成，简历与面试流程同步正常。",
        status: "正常",
      },
      {
        id: "monitor-02-api-02",
        name: "绩效台账",
        note: "权限申请仍未通过，关键字段为空。",
        status: "异常",
      },
    ],
    deviceDiagnostics: [
      {
        id: "monitor-02-device-01",
        name: "华南弹性节点 02",
        note: "早高峰时段负载偏高，需观察后续同步延迟。",
        status: "关注",
      },
      {
        id: "monitor-02-device-02",
        name: "LeDeep Edge Mini × 1",
        note: "本地设备运行稳定，心跳正常。",
        status: "正常",
      },
    ],
    trends: [
      { label: "03-25", alertCount: 1, completionRate: 84, messageVolume: 410, onlineRate: 100 },
      { label: "03-26", alertCount: 2, completionRate: 85, messageVolume: 436, onlineRate: 100 },
      { label: "03-27", alertCount: 2, completionRate: 86, messageVolume: 452, onlineRate: 100 },
      { label: "03-28", alertCount: 3, completionRate: 87, messageVolume: 468, onlineRate: 100 },
      { label: "03-29", alertCount: 2, completionRate: 87, messageVolume: 472, onlineRate: 100 },
    ],
  },
  {
    id: "monitor-03",
    customerName: "东岸家居品牌",
    scenarioName: "基于 VOC 的产品创新",
    assignedToId: "fde-engineer-luzhou",
    health: "risk",
    activeExperts: 4,
    onlineExperts: 3,
    issueCount: 4,
    messageVolume24h: 688,
    taskCompletionRate: 74,
    lastHeartbeat: "11 分钟前",
    alertSummary: "竞品爬取规则变更，VOC 评论流中断 2 小时。",
    highlights: ["评论采集恢复中", "图文产能仍可正常产出", "新品会建议待补全竞品数据"],
    alerts: [
      {
        id: "monitor-03-alert-01",
        title: "竞品评论采集中断",
        detail: "竞品站点规则调整导致评论采集中断 2 小时，VOC 数据不完整。",
        sourceType: "接口",
        sourceName: "竞品评论抓取接口",
        severity: "高",
        status: "处理中",
        ownerId: "fde-engineer-luzhou",
        createdAt: "2026-03-29 07:55",
        resolution: "正在更新抓取规则并补采最近两小时评论样本。",
      },
      {
        id: "monitor-03-alert-02",
        title: "新品图色差异常",
        detail: "夏季系列商品主图在 12 款 SKU 上出现综合色偏差。",
        sourceType: "专家",
        sourceName: "内容生产官",
        severity: "中",
        status: "待确认",
        ownerId: "fde-engineer-luzhou",
        createdAt: "2026-03-29 09:20",
        resolution: "",
      },
      {
        id: "monitor-03-alert-03",
        title: "云端节点负载升高",
        detail: "VOC 聚类高峰期云端节点 CPU 占用持续高于 85%。",
        sourceType: "设备",
        sourceName: "华东云边节点 05",
        severity: "中",
        status: "待确认",
        ownerId: "fde-engineer-luzhou",
        createdAt: "2026-03-29 10:05",
        resolution: "",
      },
    ],
    agentDiagnostics: [
      {
        id: "monitor-03-agent-01",
        name: "内容生产官",
        note: "图文产出正常，但部分彩色商品主图出现色差偏移。",
        status: "关注",
      },
      {
        id: "monitor-03-agent-02",
        name: "新品建议官",
        note: "VOC 评论流不完整，新品建议可信度下降。",
        status: "异常",
      },
    ],
    apiDiagnostics: [
      {
        id: "monitor-03-api-01",
        name: "竞品评论抓取接口",
        note: "站点规则变更，当前补采进行中。",
        status: "异常",
      },
      {
        id: "monitor-03-api-02",
        name: "商品图素材库",
        note: "素材库存取正常。",
        status: "正常",
      },
    ],
    deviceDiagnostics: [
      {
        id: "monitor-03-device-01",
        name: "华东云边节点 05",
        note: "高峰期 CPU 占用偏高，需观察扩容。",
        status: "关注",
      },
      {
        id: "monitor-03-device-02",
        name: "LeDeep Box Studio × 2",
        note: "本地渲染设备正常运行。",
        status: "正常",
      },
    ],
    trends: [
      { label: "03-25", alertCount: 2, completionRate: 79, messageVolume: 612, onlineRate: 100 },
      { label: "03-26", alertCount: 2, completionRate: 78, messageVolume: 644, onlineRate: 100 },
      { label: "03-27", alertCount: 3, completionRate: 77, messageVolume: 668, onlineRate: 95 },
      { label: "03-28", alertCount: 4, completionRate: 75, messageVolume: 680, onlineRate: 95 },
      { label: "03-29", alertCount: 4, completionRate: 74, messageVolume: 688, onlineRate: 75 },
    ],
  },
];

/**
 * 数据回流 Agent 指标。
 */
export const FDE_FEEDBACK_AGENTS: FdeFeedbackAgentItem[] = [
  {
    id: "feedback-01",
    agentName: "经营收入师",
    customerName: "百汇零售",
    assignedToId: "fde-engineer-chenlan",
    scenarioName: "门店经营日清 + 财务对账",
    resolutionRate: 96,
    triggerCount: 426,
    evolutionScore: 78,
    lastEvolvedAt: "2026-03-20",
    skillTags: ["营收汇总", "退货识别", "缺货归因"],
    issueSignals: [
      {
        id: "feedback-01-signal-01",
        category: "规则误判",
        detail: "新品门店在晨报中被合并到常规门店口径，影响老板阅读。",
        impactedSkill: "营收汇总",
        sampleCount: 2,
        title: "新品门店口径需要细化",
      },
      {
        id: "feedback-01-signal-02",
        category: "数据延迟",
        detail: "夜班门店回流晚于晨报生成窗口，导致早报缺少最后一轮数据。",
        impactedSkill: "缺货归因",
        sampleCount: 2,
        title: "夜班数据延迟 12 分钟",
      },
    ],
    samples: [
      {
        id: "feedback-01-sample-01",
        createdAt: "2026-03-28 07:56",
        expectedReply: "晨报中单列新品试点门店，并给出缺货预警明细。",
        issueCategory: "规则误判",
        observedReply: "新品门店被归并到全部门店统计，缺少单独提示。",
        question: "请输出昨天新品试点门店经营简报。",
        signalId: "feedback-01-signal-01",
      },
      {
        id: "feedback-01-sample-02",
        createdAt: "2026-03-29 08:03",
        expectedReply: "补入夜班销量与库存变动，再生成晨报。",
        issueCategory: "数据延迟",
        observedReply: "晨报已生成，但缺少夜班 3 家门店的数据。",
        question: "请生成今天 8 点的经营晨报。",
        signalId: "feedback-01-signal-02",
      },
    ],
    comparison: {
      beforeSummary: "夜班门店常出现缺数，新品门店口径也不够细。",
      afterSummary: "补入夜班兜底和新品门店专栏后，晨报可直接用于老板会。",
    },
    manualRemark: "优先处理夜班数据补齐，再细化新品门店视图。",
    recommendation: "建议基于夜班门店样本追加一轮报表补全训练。",
  },
  {
    id: "feedback-02",
    agentName: "对账核验师",
    customerName: "百汇零售",
    assignedToId: "fde-engineer-chenlan",
    scenarioName: "门店经营日清 + 财务对账",
    resolutionRate: 92,
    triggerCount: 318,
    evolutionScore: 84,
    lastEvolvedAt: "2026-03-18",
    skillTags: ["流水核对", "退款异常", "周均对比"],
    issueSignals: [
      {
        id: "feedback-02-signal-01",
        category: "规则误判",
        detail: "周末退款波动阈值过低，导致正常波动也被标红。",
        impactedSkill: "退款异常",
        sampleCount: 2,
        title: "周末退款波动阈值偏保守",
      },
      {
        id: "feedback-02-signal-02",
        category: "数据延迟",
        detail: "门店维度流水聚合高峰时响应较慢，影响核验效率。",
        impactedSkill: "周均对比",
        sampleCount: 2,
        title: "门店维度聚合需要提速",
      },
    ],
    samples: [
      {
        id: "feedback-02-sample-01",
        createdAt: "2026-03-27 19:40",
        expectedReply: "识别本周末退款波动属于促销活动影响，无需告警。",
        issueCategory: "规则误判",
        observedReply: "系统将正常退款波动判定为异常，并触发红色告警。",
        question: "请判断周末退款是否异常。",
        signalId: "feedback-02-signal-01",
      },
      {
        id: "feedback-02-sample-02",
        createdAt: "2026-03-28 13:12",
        expectedReply: "3 秒内返回门店维度核验结果。",
        issueCategory: "数据延迟",
        observedReply: "门店维度聚合耗时 8 秒，影响财务复核节奏。",
        question: "请按门店输出退款核验详情。",
        signalId: "feedback-02-signal-02",
      },
    ],
    comparison: {
      beforeSummary: "周末误报偏多，财务核验峰值时响应偏慢。",
      afterSummary: "阈值重算和聚合提速后，可减少误报并缩短复核时间。",
    },
    manualRemark: "本轮先把节假日退款阈值拉准，再处理聚合性能。",
    recommendation: "追加节假日退款样本，优化异常阈值判断。",
  },
  {
    id: "feedback-03",
    agentName: "招聘助手",
    customerName: "新锐科技",
    assignedToId: "fde-engineer-hejin",
    scenarioName: "招聘协同 + 组织风险预警",
    resolutionRate: 88,
    triggerCount: 215,
    evolutionScore: 69,
    lastEvolvedAt: "2026-03-15",
    skillTags: ["简历筛选", "JD 拆写", "面试问题生成"],
    issueSignals: [
      {
        id: "feedback-03-signal-01",
        category: "知识缺口",
        detail: "技术岗关键词覆盖不足，导致匹配过宽。",
        impactedSkill: "简历筛选",
        sampleCount: 2,
        title: "技术岗匹配偏宽",
      },
      {
        id: "feedback-03-signal-02",
        category: "规则误判",
        detail: "候选人排序对项目经历和学历权重切换不稳定。",
        impactedSkill: "面试问题生成",
        sampleCount: 2,
        title: "候选人优先级排序还不稳定",
      },
    ],
    samples: [
      {
        id: "feedback-03-sample-01",
        createdAt: "2026-03-28 15:22",
        expectedReply: "优先推荐有 Java 高并发经验的候选人。",
        issueCategory: "知识缺口",
        observedReply: "系统将偏前端背景候选人也列入前 3。",
        question: "请筛选高级后端工程师候选人。",
        signalId: "feedback-03-signal-01",
      },
      {
        id: "feedback-03-sample-02",
        createdAt: "2026-03-29 09:18",
        expectedReply: "保持上一版排序逻辑，优先项目匹配度高的候选人。",
        issueCategory: "规则误判",
        observedReply: "排序结果在学历和项目经历间切换过于频繁。",
        question: "请对这批候选人重新排序。",
        signalId: "feedback-03-signal-02",
      },
    ],
    comparison: {
      beforeSummary: "高技术岗位筛选偏宽，排序稳定性不足。",
      afterSummary: "结合录用样本重算权重后，可稳定推荐更高匹配候选人。",
    },
    manualRemark: "建议只选技术岗相关信号先做一轮进化，避免一次改太多。",
    recommendation: "建议基于近 50 份录用案例做一次匹配权重进化。",
  },
  {
    id: "feedback-04",
    agentName: "内容生产官",
    customerName: "东岸家居品牌",
    assignedToId: "fde-engineer-luzhou",
    scenarioName: "基于 VOC 的产品创新",
    resolutionRate: 85,
    triggerCount: 502,
    evolutionScore: 73,
    lastEvolvedAt: "2026-03-12",
    skillTags: ["商品主图生成", "商品图合成", "风格迁移"],
    issueSignals: [
      {
        id: "feedback-04-signal-01",
        category: "规则误判",
        detail: "同系列场景图在光感和背景构图上不一致。",
        impactedSkill: "风格迁移",
        sampleCount: 2,
        title: "场景图风格一致性不足",
      },
      {
        id: "feedback-04-signal-02",
        category: "幻觉回答",
        detail: "夏季系列商品主图出现综合色偏差，影响视觉统一。",
        impactedSkill: "商品主图生成",
        sampleCount: 2,
        title: "主图色差在夏季系列偏明显",
      },
    ],
    samples: [
      {
        id: "feedback-04-sample-01",
        createdAt: "2026-03-28 16:10",
        expectedReply: "同系列场景图应保持统一背景光感和构图。",
        issueCategory: "规则误判",
        observedReply: "同一系列图像中背景亮度和透视差异明显。",
        question: "请批量生成夏季新品场景图。",
        signalId: "feedback-04-signal-01",
      },
      {
        id: "feedback-04-sample-02",
        createdAt: "2026-03-29 09:45",
        expectedReply: "主图颜色与实物样衣保持一致。",
        issueCategory: "幻觉回答",
        observedReply: "海蓝色主图偏向青绿色，和样衣不一致。",
        question: "请输出这组夏季单品主图。",
        signalId: "feedback-04-signal-02",
      },
    ],
    comparison: {
      beforeSummary: "同系列图像风格和色彩统一性不足。",
      afterSummary: "补充风格约束与色差样本后，可统一系列视觉风格。",
    },
    manualRemark: "建议优先处理夏季系列色差，再回收场景图风格问题。",
    recommendation: "建议以本周新品图回流触发一次风格一致性进化。",
  },
];

/**
 * 进化任务。
 */
export const FDE_EVOLUTION_TASKS: FdeEvolutionTaskItem[] = [
  {
    id: "evo-01",
    agentName: "内容生产官",
    customerName: "东岸家居品牌",
    assignedToId: "fde-engineer-luzhou",
    status: "训练中",
    progress: 62,
    versionCandidate: "v3.8.0",
    source: "手动触发",
    startedAt: "2026-03-27 10:40",
    expectedFinishAt: "2026-03-28 19:00",
    submittedAt: "",
    reviewedAt: "",
    reviewedById: "",
    releaseId: null,
    changedSkills: ["商品图合成", "风格一致性", "模板检索"],
    sourceSignalIds: ["feedback-04-signal-01", "feedback-04-signal-02"],
    sourceSignalTitles: ["场景图风格一致性不足", "主图色差在夏季系列偏明显"],
    diffSummary: "补充风格一致性约束和夏季系列色差样本，统一主图风格。",
    manualNote: "优先保证夏季新品会所需的主图稳定输出。",
    summary: "基于 280 张新品图和 64 条 VOC 评论，提升新品会前图文产能。",
    reviewRecords: [],
    timeline: [
      buildTimelineItem(
        "timeline-evo-01-01",
        "创建任务",
        "基于东岸家居品牌最新 VOC 回流创建进化任务。",
        "2026-03-27 10:40",
      ),
      buildTimelineItem(
        "timeline-evo-01-02",
        "开始训练",
        "已进入训练阶段，正在生成新的商品图风格一致性候选版本。",
        "2026-03-27 11:10",
      ),
    ],
  },
  {
    id: "evo-02",
    agentName: "招聘助手",
    customerName: "新锐科技",
    assignedToId: "fde-engineer-hejin",
    status: "待审核",
    progress: 100,
    versionCandidate: "v2.3.1",
    source: "自动回流",
    startedAt: "2026-03-26 09:00",
    expectedFinishAt: "2026-03-27 16:00",
    submittedAt: "2026-03-27 16:20",
    reviewedAt: "",
    reviewedById: "",
    releaseId: null,
    changedSkills: ["技术岗匹配", "候选人优先级排序"],
    sourceSignalIds: ["feedback-03-signal-01", "feedback-03-signal-02"],
    sourceSignalTitles: ["技术岗匹配偏宽", "候选人优先级排序还不稳定"],
    diffSummary: "重算技术岗标签权重，并稳定候选人排序策略。",
    manualNote: "结合近 50 份录用案例做权重校准。",
    summary: "完成 50 份录用案例回灌，需要 FDE 审核后进入灰度。",
    reviewRecords: [],
    timeline: [
      buildTimelineItem(
        "timeline-evo-02-01",
        "创建任务",
        "自动回流识别技术岗匹配偏差，已创建进化任务。",
        "2026-03-26 09:00",
      ),
      buildTimelineItem(
        "timeline-evo-02-02",
        "开始训练",
        "已完成技术岗标签权重校准与排序策略重训。",
        "2026-03-26 10:30",
      ),
      buildTimelineItem(
        "timeline-evo-02-03",
        "提交审核",
        "候选版本已完成训练，等待王琳审核。",
        "2026-03-27 16:20",
      ),
    ],
  },
  {
    id: "evo-03",
    agentName: "对账核验师",
    customerName: "百汇零售",
    assignedToId: "fde-engineer-chenlan",
    status: "排队中",
    progress: 8,
    versionCandidate: "v1.9.0",
    source: "手动触发",
    startedAt: "2026-03-28 09:30",
    expectedFinishAt: "2026-03-29 14:00",
    submittedAt: "",
    reviewedAt: "",
    reviewedById: "",
    releaseId: null,
    changedSkills: ["节假日退款阈值", "门店聚合速度"],
    sourceSignalIds: ["feedback-02-signal-01", "feedback-02-signal-02"],
    sourceSignalTitles: ["周末退款波动阈值偏保守", "门店维度聚合需要提速"],
    diffSummary: "调整节假日退款阈值并优化门店维度核验性能。",
    manualNote: "优先减少财务误报，再改善峰值时的聚合耗时。",
    summary: "补入周末退款异常样本，准备提升核验准确率与响应速度。",
    reviewRecords: [],
    timeline: [
      buildTimelineItem(
        "timeline-evo-03-01",
        "创建任务",
        "由 FDE 手动选中信号后创建核验师进化任务。",
        "2026-03-28 09:30",
      ),
    ],
  },
];

/**
 * 版本推送记录。
 */
export const FDE_RELEASE_PUSHES: FdeReleasePushItem[] = [
  {
    id: "release-01",
    agentName: "经营收入师",
    version: "v1.7.2",
    sourceTaskId: null,
    assignedToId: "fde-engineer-chenlan",
    grayPercent: 100,
    targetCustomers: ["百汇零售", "智联制造"],
    availableCustomers: ["百汇零售", "智联制造", "新锐科技"],
    status: "已完成",
    pushedAt: "2026-03-25 20:00",
    adoptionRate: 100,
    rollbackReason: "",
    summary: "补齐夜班数据兜底逻辑，晨报生成提前 12 分钟。",
    releaseSections: [
      {
        title: "本次变更",
        items: ["增加夜班兜底规则", "晨报模版新增门店缺货摘要", "提升 28 家门店合并速度"],
      },
      {
        title: "目标客户",
        items: ["百汇零售", "智联制造"],
      },
      {
        title: "观察指标",
        items: ["晨报生成时长", "夜班缺失数据补齐率", "门店日报人工修正次数"],
      },
    ],
    customerResults: [
      {
        id: "release-01-customer-01",
        customerName: "百汇零售",
        status: "已完成",
        rolloutPercent: 100,
        adoptionRate: 100,
        feedback: "财务晨报已稳定使用新版规则，误报明显下降。",
        lastUpdatedAt: "2026-03-25 20:00",
      },
      {
        id: "release-01-customer-02",
        customerName: "智联制造",
        status: "已完成",
        rolloutPercent: 100,
        adoptionRate: 100,
        feedback: "门店动作同步时延下降，老板晨会直接使用新版日报。",
        lastUpdatedAt: "2026-03-25 20:00",
      },
      {
        id: "release-01-customer-03",
        customerName: "新锐科技",
        status: "待发布",
        rolloutPercent: 0,
        adoptionRate: 0,
        feedback: "当前未纳入本轮经营收入师的目标范围。",
        lastUpdatedAt: "2026-03-24 18:00",
      },
    ],
    timeline: [
      buildTimelineItem(
        "timeline-release-01-01",
        "创建发布单",
        "经营收入师 v1.7.2 发布单已创建，准备对重点客户推送。",
        "2026-03-24 18:20",
      ),
      buildTimelineItem(
        "timeline-release-01-02",
        "开始灰度",
        "已先对百汇零售与智联制造启动 50% 灰度观察。",
        "2026-03-25 10:00",
      ),
      buildTimelineItem(
        "timeline-release-01-03",
        "全量发布",
        "观察结果稳定，已完成目标客户全量推送。",
        "2026-03-25 20:00",
      ),
    ],
  },
  {
    id: "release-02",
    agentName: "招聘助手",
    version: "v2.3.1",
    sourceTaskId: null,
    assignedToId: "fde-engineer-hejin",
    grayPercent: 30,
    targetCustomers: ["新锐科技"],
    availableCustomers: ["新锐科技", "百汇零售", "智联制造"],
    status: "灰度中",
    pushedAt: "2026-03-28 11:20",
    adoptionRate: 46,
    rollbackReason: "",
    summary: "技术岗筛选模型进入 30% 灰度，观察命中率和人工复核率。",
    releaseSections: [
      {
        title: "本次变更",
        items: ["技术岗匹配权重重算", "候选人优先级排序更稳", "面试问题生成增加岗位画像"],
      },
      {
        title: "目标客户",
        items: ["新锐科技"],
      },
      {
        title: "观察指标",
        items: ["技术岗命中率", "人工复核率", "录用转化率"],
      },
    ],
    customerResults: [
      {
        id: "release-02-customer-01",
        customerName: "新锐科技",
        status: "灰度中",
        rolloutPercent: 30,
        adoptionRate: 46,
        feedback: "技术岗筛选命中率提升，但个别候选人排序仍需观察。",
        lastUpdatedAt: "2026-03-28 11:20",
      },
      {
        id: "release-02-customer-02",
        customerName: "百汇零售",
        status: "待发布",
        rolloutPercent: 0,
        adoptionRate: 0,
        feedback: "当前不在本轮招聘助手灰度名单内。",
        lastUpdatedAt: "2026-03-28 10:30",
      },
      {
        id: "release-02-customer-03",
        customerName: "智联制造",
        status: "待发布",
        rolloutPercent: 0,
        adoptionRate: 0,
        feedback: "当前不在本轮招聘助手灰度名单内。",
        lastUpdatedAt: "2026-03-28 10:30",
      },
    ],
    timeline: [
      buildTimelineItem(
        "timeline-release-02-01",
        "创建发布单",
        "招聘助手 v2.3.1 发布单已准备完成。",
        "2026-03-28 09:50",
      ),
      buildTimelineItem(
        "timeline-release-02-02",
        "开始灰度",
        "已对新锐科技启动 30% 灰度观察。",
        "2026-03-28 11:20",
      ),
    ],
  },
  {
    id: "release-03",
    agentName: "内容生产官",
    version: "v3.7.4",
    sourceTaskId: null,
    assignedToId: "fde-engineer-luzhou",
    grayPercent: 40,
    targetCustomers: ["东岸家居品牌", "环球电商"],
    availableCustomers: ["东岸家居品牌", "环球电商", "百汇零售"],
    status: "待发布",
    pushedAt: "2026-03-29 09:10",
    adoptionRate: 0,
    rollbackReason: "",
    summary: "等待最新一轮 VOC 图像风格进化完成后统一推送。",
    releaseSections: [
      {
        title: "本次变更",
        items: ["商品图风格一致性增强", "夏季系列色差修正", "模板召回命中率提升"],
      },
      {
        title: "目标客户",
        items: ["东岸家居品牌", "环球电商"],
      },
      {
        title: "观察指标",
        items: ["主图色差反馈", "风格一致性评分", "模板召回命中率"],
      },
    ],
    customerResults: [
      {
        id: "release-03-customer-01",
        customerName: "东岸家居品牌",
        status: "待发布",
        rolloutPercent: 0,
        adoptionRate: 0,
        feedback: "等待配置灰度比例后启动首批推送。",
        lastUpdatedAt: "2026-03-29 09:10",
      },
      {
        id: "release-03-customer-02",
        customerName: "环球电商",
        status: "待发布",
        rolloutPercent: 0,
        adoptionRate: 0,
        feedback: "等待配置灰度比例后启动首批推送。",
        lastUpdatedAt: "2026-03-29 09:10",
      },
      {
        id: "release-03-customer-03",
        customerName: "百汇零售",
        status: "待发布",
        rolloutPercent: 0,
        adoptionRate: 0,
        feedback: "当前未纳入内容生产官本轮目标范围。",
        lastUpdatedAt: "2026-03-29 09:10",
      },
    ],
    timeline: [
      buildTimelineItem(
        "timeline-release-03-01",
        "创建发布单",
        "内容生产官新版本已进入发布准备阶段，待配置客户范围。",
        "2026-03-29 09:10",
      ),
    ],
  },
];

/**
 * 默认线索表单。
 */
export const createInitialFdeLeadFormState = (): FdeLeadFormState => ({
  companyName: "",
  contactName: "",
  phone: "",
  interestedScenes: [],
  source: "官网留资",
  priority: "中",
  budgetLabel: "",
  nextFollowUpAt: "",
  summary: "",
  remark: "",
  assignedToId: null,
});
