import type {
  FdeDeliveryOrderItem,
  FdeDeliveryStepItem,
  FdeEvolutionTaskItem,
  FdeFeedbackAgentItem,
  FdeLeadFormState,
  FdeLeadItem,
  FdeOperationsCustomerItem,
  FdeOpportunityItem,
  FdeReleasePushItem,
  FdeTeamMemberItem,
  FdeWorkbenchTabItem,
} from "@/feature/fde/types";

/**
 * FDE 工作台导航。
 */
export const FDE_WORKBENCH_TABS: FdeWorkbenchTabItem[] = [
  { key: "opportunities", label: "商机工作台", description: "团队商机与转化漏斗" },
  { key: "leads", label: "线索工单", description: "线索录入、分配与状态流转" },
  { key: "delivery", label: "配置交付", description: "正式订单交付与专家团配置" },
  { key: "operations", label: "运营监控", description: "客户 AI 专家团实时运行状态" },
  { key: "feedback", label: "数据回流看板", description: "按 Agent 查看回流数据与进化建议" },
  { key: "evolution", label: "进化任务管理", description: "训练中与待审核的进化任务" },
  { key: "releases", label: "版本推送", description: "升级后的 Agent 推送记录" },
];

/**
 * FDE 交付步骤。
 */
export const FDE_DELIVERY_STEPS: FdeDeliveryStepItem[] = [
  { key: "customerConfirm", label: "客户信息确认" },
  { key: "deviceConfig", label: "设备配置" },
  { key: "agentConfig", label: "Agent配置" },
  { key: "apiTest", label: "API测试" },
  { key: "memberInit", label: "成员初始化" },
  { key: "preflight", label: "发货前检查" },
];

/**
 * FDE 团队成员。
 */
export const FDE_TEAM_MEMBERS: FdeTeamMemberItem[] = [
  {
    id: "fde-leader-wanglin",
    name: "王琳",
    title: "FDE 团队负责人",
    role: "leader",
    status: "online",
    focusScenes: ["商机诊断", "交付策略", "版本审核"],
    avatarSeed: "wang-lin",
  },
  {
    id: "fde-engineer-chenlan",
    name: "陈岚",
    title: "资深交付工程师",
    role: "engineer",
    status: "online",
    focusScenes: ["经营管理", "销售增长", "数据回流"],
    avatarSeed: "chen-lan",
  },
  {
    id: "fde-engineer-luzhou",
    name: "陆舟",
    title: "FDE 配置工程师",
    role: "engineer",
    status: "busy",
    focusScenes: ["内容创作", "本地设备部署", "版本灰度"],
    avatarSeed: "lu-zhou",
  },
  {
    id: "fde-engineer-hejin",
    name: "何晋",
    title: "FDE 运营工程师",
    role: "engineer",
    status: "online",
    focusScenes: ["客户服务", "线索工单", "运营监控"],
    avatarSeed: "he-jin",
  },
];

/**
 * FDE 商机数据。
 */
export const FDE_OPPORTUNITIES: FdeOpportunityItem[] = [
  {
    id: "opp-01",
    companyName: "智联制造",
    scenarioName: "经营日报 + 门店动作同步",
    industry: "制造零售",
    stage: "初步沟通",
    amountWan: 18.8,
    winRate: 32,
    ownerId: "fde-engineer-chenlan",
    nextAction: "安排老板演示经营日报链路",
    nextActionDate: "2026-03-31",
    source: "官网咨询",
    summary: "对门店日报、排班和缺货风险特别关注。",
  },
  {
    id: "opp-02",
    companyName: "环球电商",
    scenarioName: "基于 VOC 的产品创新",
    industry: "跨境电商",
    stage: "产品演示",
    amountWan: 26.5,
    winRate: 52,
    ownerId: "fde-engineer-luzhou",
    nextAction: "补演 VOC 看板和产品创新节奏",
    nextActionDate: "2026-04-02",
    source: "FDE 服务页",
    summary: "老板希望先用评论和竞品动态跑通新品会决策。",
  },
  {
    id: "opp-03",
    companyName: "创新医疗",
    scenarioName: "销售线索分层 + 战报推送",
    industry: "医疗服务",
    stage: "方案推荐",
    amountWan: 34.2,
    winRate: 63,
    ownerId: "fde-engineer-chenlan",
    nextAction: "输出正式方案和设备部署说明",
    nextActionDate: "2026-03-30",
    source: "老板转介绍",
    summary: "重点看多院区销售协同和一线跟进质检。",
  },
  {
    id: "opp-04",
    companyName: "新锐科技",
    scenarioName: "招聘协同 + 组织风险预警",
    industry: "科技服务",
    stage: "商务谈判",
    amountWan: 19.7,
    winRate: 84,
    ownerId: "fde-engineer-hejin",
    nextAction: "确认采购清单与本地设备数量",
    nextActionDate: "2026-03-29",
    source: "线下活动",
    summary: "已确认试点部门和 PO，进入商务条款确认。",
  },
  {
    id: "opp-05",
    companyName: "百汇零售",
    scenarioName: "门店经营日清 + 财务对账",
    industry: "零售连锁",
    stage: "已成交",
    amountWan: 49.0,
    winRate: 100,
    ownerId: "fde-engineer-chenlan",
    nextAction: "进入配置交付与设备发货",
    nextActionDate: "2026-03-28",
    source: "官网咨询",
    summary: "签约首期 28 家门店，FDE 已进入设备配置阶段。",
  },
  {
    id: "opp-06",
    companyName: "极客供应链",
    scenarioName: "供应链异常预警 + 补位建议",
    industry: "供应链",
    stage: "产品演示",
    amountWan: 22.4,
    winRate: 45,
    ownerId: "fde-engineer-hejin",
    nextAction: "安排对接 ERP 与库存 API",
    nextActionDate: "2026-04-01",
    source: "FDE 服务页",
    summary: "需要把采购、库存和交付预警汇成一套 AI 协作流。",
  },
];

/**
 * FDE 线索工单数据。
 */
export const FDE_LEADS: FdeLeadItem[] = [
  {
    id: "lead-01",
    companyName: "某跨境电商有限公司",
    contactName: "王总",
    phone: "138xxxx5678",
    interestedScenes: ["AI CEO 教练", "电商运营专家"],
    source: "官网留资",
    createdAt: "2026-03-27 14:32",
    status: "新线索",
    assignedToId: "fde-engineer-chenlan",
    budgetLabel: "首期预算 ¥12-20 万",
    summary: "老板希望先从经营日报和销售跟进入手，最快 2 周内启动试点。",
    remark: "官网咨询后 15 分钟内回拨过，但仍需要补充试点门店数量。",
  },
  {
    id: "lead-02",
    companyName: "某制造企业",
    contactName: "张董",
    phone: "137xxxx2233",
    interestedScenes: ["供应链协同专家", "经营看板专家"],
    source: "FDE 服务页留资",
    createdAt: "2026-03-27 11:20",
    status: "新线索",
    assignedToId: "fde-engineer-hejin",
    budgetLabel: "首期预算 ¥8-15 万",
    summary: "关注多工厂排产建议和异常预警，希望先做供应链试点。",
    remark: "老板明确表示需要先看本地设备部署方式和安全方案。",
  },
  {
    id: "lead-03",
    companyName: "东岸家居品牌",
    contactName: "林薇",
    phone: "139xxxx1168",
    interestedScenes: ["内容创作专家", "商机洞察专家"],
    source: "老板转介绍",
    createdAt: "2026-03-26 18:04",
    status: "跟进中",
    assignedToId: "fde-engineer-luzhou",
    budgetLabel: "首期预算 ¥15-30 万",
    summary: "重点是基于 VOC 的新品决策和图文内容批量生产。",
    remark: "已经发了演示链接，下周三安排第二轮方案会。",
  },
  {
    id: "lead-04",
    companyName: "百汇零售",
    contactName: "刘总",
    phone: "136xxxx9182",
    interestedScenes: ["经营看板专家", "财务对账专家", "招聘助手"],
    source: "官网留资",
    createdAt: "2026-03-22 09:10",
    status: "已成单",
    assignedToId: "fde-engineer-chenlan",
    budgetLabel: "签约金额 ¥49 万",
    summary: "已签首期 28 家门店试点，进入配置交付。",
    remark: "需要同步门店缺货、退货、招聘和经营简报。",
  },
  {
    id: "lead-05",
    companyName: "新锐科技",
    contactName: "赵慧",
    phone: "135xxxx1190",
    interestedScenes: ["AI CEO 教练", "招聘助手"],
    source: "线下活动",
    createdAt: "2026-03-19 17:45",
    status: "已成单",
    assignedToId: "fde-engineer-hejin",
    budgetLabel: "签约金额 ¥19.7 万",
    summary: "组织管理与招聘协同试点已确认签约。",
    remark: "需要本地设备 + 云端管理混合部署。",
  },
  {
    id: "lead-06",
    companyName: "南城服务集团",
    contactName: "杜斌",
    phone: "158xxxx8872",
    interestedScenes: ["客服质检官", "销售线索官"],
    source: "官网留资",
    createdAt: "2026-03-18 15:12",
    status: "已放弃",
    assignedToId: "fde-engineer-hejin",
    budgetLabel: "预算未明确",
    summary: "预算和组织优先级都没有确定，短期内不推进。",
    remark: "建议 60 天后再回访。",
  },
];

/**
 * FDE 配置交付工单。
 */
export const FDE_DELIVERY_ORDERS: FdeDeliveryOrderItem[] = [
  {
    id: "delivery-01",
    leadId: "lead-04",
    customerName: "百汇零售",
    orderNo: "FDE-20260322-001",
    assignedToId: "fde-engineer-chenlan",
    industry: "零售连锁",
    scenarioName: "门店经营日清 + 财务对账",
    currentStep: "agentConfig",
    stepProgress: 48,
    deviceConfig: {
      mode: "本地设备",
      cloudNodeName: "华东云边节点 03",
      localDeviceName: "LeDeep Box Pro × 3",
      pairingCode: "OS-84DK-2P1R",
      osOwner: "LeDeep OS",
      region: "上海 / 苏州",
    },
    expertNames: ["经营收入师", "对账核验师", "补位协同师", "晨报生成师"],
    apiTargets: ["ERP 订单接口", "门店排班接口", "招聘系统 API"],
    memberCount: 36,
    createdAt: "2026-03-22 10:30",
    launchTargetDate: "2026-04-08",
    preflightChecks: ["设备序列号已确认", "接口白名单待最终核验", "门店成员名单已收齐"],
  },
  {
    id: "delivery-02",
    leadId: "lead-05",
    customerName: "新锐科技",
    orderNo: "FDE-20260319-003",
    assignedToId: "fde-engineer-hejin",
    industry: "科技服务",
    scenarioName: "招聘协同 + 组织风险预警",
    currentStep: "deviceConfig",
    stepProgress: 26,
    deviceConfig: {
      mode: "混合部署",
      cloudNodeName: "华南弹性节点 02",
      localDeviceName: "LeDeep Edge Mini × 1",
      pairingCode: "待 OS 提供",
      osOwner: "LeDeep OS",
      region: "深圳",
    },
    expertNames: ["招聘助手", "组织风险雷达", "中层表现分析师"],
    apiTargets: ["ATS API", "企业微信通讯录", "绩效台账"],
    memberCount: 18,
    createdAt: "2026-03-20 09:00",
    launchTargetDate: "2026-04-12",
    preflightChecks: ["本地设备型号已锁定", "客户侧 API 权限申请中", "岗位地图已确认"],
  },
];

/**
 * 运营监控客户。
 */
export const FDE_OPERATIONS_CUSTOMERS: FdeOperationsCustomerItem[] = [
  {
    id: "monitor-01",
    customerName: "百汇零售",
    scenarioName: "门店经营日清 + 财务对账",
    assignedToId: "fde-engineer-chenlan",
    health: "healthy",
    activeExperts: 4,
    onlineExperts: 4,
    issueCount: 1,
    messageVolume24h: 1268,
    taskCompletionRate: 96,
    lastHeartbeat: "2 分钟前",
    alertSummary: "招聘缺口预警 1 条，其余运行稳定。",
    highlights: ["晨报 7:58 自动生成", "28 家门店均已回流日报", "退货异常识别准确率 93%"],
  },
  {
    id: "monitor-02",
    customerName: "新锐科技",
    scenarioName: "招聘协同 + 组织风险预警",
    assignedToId: "fde-engineer-hejin",
    health: "attention",
    activeExperts: 3,
    onlineExperts: 3,
    issueCount: 2,
    messageVolume24h: 472,
    taskCompletionRate: 87,
    lastHeartbeat: "6 分钟前",
    alertSummary: "组织风险雷达缺一组部门权限，需要补配 API。",
    highlights: ["候选人筛选已跑通", "中层表现分析待接绩效数据", "设备心跳正常"],
  },
  {
    id: "monitor-03",
    customerName: "东岸家居品牌",
    scenarioName: "基于 VOC 的产品创新",
    assignedToId: "fde-engineer-luzhou",
    health: "risk",
    activeExperts: 4,
    onlineExperts: 3,
    issueCount: 4,
    messageVolume24h: 688,
    taskCompletionRate: 74,
    lastHeartbeat: "11 分钟前",
    alertSummary: "竞品爬取规则变更，VOC 评论流中断 2 小时。",
    highlights: ["评论采集恢复中", "图文产能仍可正常产出", "新品会建议待补全竞品数据"],
  },
];

/**
 * 数据回流 Agent 指标。
 */
export const FDE_FEEDBACK_AGENTS: FdeFeedbackAgentItem[] = [
  {
    id: "feedback-01",
    agentName: "经营收入师",
    customerName: "百汇零售",
    assignedToId: "fde-engineer-chenlan",
    scenarioName: "门店经营日清 + 财务对账",
    resolutionRate: 96,
    triggerCount: 426,
    evolutionScore: 78,
    lastEvolvedAt: "2026-03-20",
    skillTags: ["营收汇总", "退货识别", "缺货归因"],
    issueSignals: ["新品门店口径需要细化", "夜班数据延迟 12 分钟"],
    recommendation: "建议基于夜班门店样本追加一轮报表补全训练。",
  },
  {
    id: "feedback-02",
    agentName: "对账核验师",
    customerName: "百汇零售",
    assignedToId: "fde-engineer-chenlan",
    scenarioName: "门店经营日清 + 财务对账",
    resolutionRate: 92,
    triggerCount: 318,
    evolutionScore: 84,
    lastEvolvedAt: "2026-03-18",
    skillTags: ["流水核对", "退款异常", "周均对比"],
    issueSignals: ["周末退款波动阈值偏保守", "门店维度聚合需要提速"],
    recommendation: "追加节假日退款样本，优化异常阈值判断。",
  },
  {
    id: "feedback-03",
    agentName: "招聘助手",
    customerName: "新锐科技",
    assignedToId: "fde-engineer-hejin",
    scenarioName: "招聘协同 + 组织风险预警",
    resolutionRate: 88,
    triggerCount: 215,
    evolutionScore: 69,
    lastEvolvedAt: "2026-03-15",
    skillTags: ["简历筛选", "JD 拆写", "面试问题生成"],
    issueSignals: ["技术岗匹配偏宽", "候选人优先级排序还不稳定"],
    recommendation: "建议基于近 50 份录用案例做一次匹配权重进化。",
  },
  {
    id: "feedback-04",
    agentName: "内容生产官",
    customerName: "东岸家居品牌",
    assignedToId: "fde-engineer-luzhou",
    scenarioName: "基于 VOC 的产品创新",
    resolutionRate: 85,
    triggerCount: 502,
    evolutionScore: 73,
    lastEvolvedAt: "2026-03-12",
    skillTags: ["商品主图生成", "商品图合成", "风格迁移"],
    issueSignals: ["场景图风格一致性不足", "主图色差在夏季系列偏明显"],
    recommendation: "建议以本周新品图回流触发一次风格一致性进化。",
  },
];

/**
 * 进化任务。
 */
export const FDE_EVOLUTION_TASKS: FdeEvolutionTaskItem[] = [
  {
    id: "evo-01",
    agentName: "内容生产官",
    customerName: "东岸家居品牌",
    assignedToId: "fde-engineer-luzhou",
    status: "训练中",
    progress: 62,
    versionCandidate: "v3.8.0",
    source: "手动触发",
    startedAt: "2026-03-27 10:40",
    expectedFinishAt: "2026-03-28 19:00",
    changedSkills: ["商品图合成", "风格一致性", "模板检索"],
    summary: "基于 280 张新品图和 64 条 VOC 评论，提升新品会前图文产能。",
  },
  {
    id: "evo-02",
    agentName: "招聘助手",
    customerName: "新锐科技",
    assignedToId: "fde-engineer-hejin",
    status: "待审核",
    progress: 100,
    versionCandidate: "v2.3.1",
    source: "自动回流",
    startedAt: "2026-03-26 09:00",
    expectedFinishAt: "2026-03-27 16:00",
    changedSkills: ["技术岗匹配", "候选人优先级排序"],
    summary: "完成 50 份录用案例回灌，需要 FDE 审核后进入灰度。",
  },
  {
    id: "evo-03",
    agentName: "对账核验师",
    customerName: "百汇零售",
    assignedToId: "fde-engineer-chenlan",
    status: "排队中",
    progress: 8,
    versionCandidate: "v1.9.0",
    source: "手动触发",
    startedAt: "2026-03-28 09:30",
    expectedFinishAt: "2026-03-29 14:00",
    changedSkills: ["节假日退款阈值", "门店聚合速度"],
    summary: "补入周末退款异常样本，准备提升核验准确率与响应速度。",
  },
];

/**
 * 版本推送记录。
 */
export const FDE_RELEASE_PUSHES: FdeReleasePushItem[] = [
  {
    id: "release-01",
    agentName: "经营收入师",
    version: "v1.7.2",
    assignedToId: "fde-engineer-chenlan",
    targetCustomers: ["百汇零售", "智联制造"],
    status: "已完成",
    pushedAt: "2026-03-25 20:00",
    adoptionRate: 100,
    summary: "补齐夜班数据兜底逻辑，晨报生成提前 12 分钟。",
    releaseNotes: ["增加夜班兜底规则", "晨报模版新增门店缺货摘要", "提升 28 家门店合并速度"],
  },
  {
    id: "release-02",
    agentName: "招聘助手",
    version: "v2.3.1",
    assignedToId: "fde-engineer-hejin",
    targetCustomers: ["新锐科技"],
    status: "灰度中",
    pushedAt: "2026-03-28 11:20",
    adoptionRate: 46,
    summary: "技术岗筛选模型进入 30% 灰度，观察命中率和人工复核率。",
    releaseNotes: ["技术岗匹配权重重算", "候选人优先级排序更稳", "面试问题生成增加岗位画像"],
  },
  {
    id: "release-03",
    agentName: "内容生产官",
    version: "v3.7.4",
    assignedToId: "fde-engineer-luzhou",
    targetCustomers: ["东岸家居品牌", "环球电商"],
    status: "待发布",
    pushedAt: "待审核",
    adoptionRate: 0,
    summary: "等待最新一轮 VOC 图像风格进化完成后统一推送。",
    releaseNotes: ["商品图风格一致性增强", "夏季系列色差修正", "模板召回命中率提升"],
  },
];

/**
 * 默认线索表单。
 */
export const createInitialFdeLeadFormState = (): FdeLeadFormState => ({
  companyName: "",
  contactName: "",
  phone: "",
  interestedScenes: [],
  source: "官网留资",
  budgetLabel: "",
  summary: "",
  remark: "",
  assignedToId: null,
});
