import type { WorkbenchAgentItem, WorkbenchAgentWorkspace } from "./types";

export const WORKBENCH_AGENT_STORE_ITEMS: WorkbenchAgentItem[] = [
  {
    id: "agent-001",
    name: "智能客服 Agent",
    version: "3.2.0",
    agentType: "metaagent",
    category: "sales",
    tags: ["内容创作", "客服"],
    description:
      "面向电商和 SaaS 企业的全渠道智能客服 Agent，集成退货政策查询、物流追踪、会员权益咨询等技能，支持多轮对话和情绪识别。",
    publisher: "Frontis 官方",
    publishTime: "2026-03-30",
    iconColor: "#667eea",
    iconText: "客",
    visibility: "public",
    skills: [
      { skillName: "智能文案生成", version: "3.0.1" },
      { skillName: "多语言翻译引擎", version: "2.4.0" },
      { skillName: "知识库问答", version: "2.0.0" },
    ],
    versions: [
      {
        version: "3.2.0",
        releaseNote: "新增情绪识别和智能转人工策略，优化多轮对话上下文保持。",
        publishTime: "2026-03-30",
        evolution: {
          skillTriggerAccuracy: "91%",
          skillTriggerAccuracyTrend: "↑13%",
          taskCompletionRate: "89%",
          taskCompletionRateTrend: "↑18%",
          qualityScore: "87%",
          qualityScoreTrend: "↑15%",
          executionTime: "128ms",
          executionTimeTrend: "↓39%",
          tokenUsage: "1240",
          tokenUsageTrend: "↓22%",
          regressionRetention: "96%",
          regressionRetentionTrend: "↑12%",
        },
        evalReport: {
          summary:
            "v3.2版本在各项核心指标上均有显著提升，特别是在Skill触发准确率和任务完成行为率方面表现突出，经过多轮测试验证，该版本已达到发布标准，建议进行部署。",
          overallScore: 92,
          overallScoreTrend: "↑15%",
          metrics: [
            { label: "Skill触发准确率", value: "91%", trend: "↑12%" },
            { label: "任务完成行为率", value: "89%", trend: "↑8%" },
            { label: "结果质量评分", value: "87%", trend: "↑22%" },
            { label: "执行耗时", value: "128ms", trend: "↓39%" },
            { label: "Token消耗量", value: "1240", trend: "↓18%" },
            { label: "回归基准保持率", value: "96%", trend: "↑12%" },
          ],
          testTime: "2026-03-28 14:30",
          testRounds: 6,
          testScenes: ["电商客服", "物流查询", "会员权益", "售后服务"],
          issues: "在复杂多轮对话场景下，工具调用成功率仍有提升空间。",
          suggestions: "优化工具调用参数验证逻辑，增加错误重试机制。",
          conclusion:
            "v3.2版本表现优秀，各项指标均已达到或超过预期目标，建议进行发布。并在生产环境中持续监控其性能表现。",
        },
      },
      {
        version: "3.0.0",
        releaseNote: "全面升级底层模型，新增退货政策和物流查询技能。",
        publishTime: "2026-02-20",
        evolution: {
          skillTriggerAccuracy: "86%",
          skillTriggerAccuracyTrend: "↑8%",
          taskCompletionRate: "82%",
          taskCompletionRateTrend: "↑10%",
          qualityScore: "83%",
          qualityScoreTrend: "↑9%",
          executionTime: "210ms",
          executionTimeTrend: "↓15%",
          tokenUsage: "1590",
          tokenUsageTrend: "↓10%",
          regressionRetention: "88%",
          regressionRetentionTrend: "↑6%",
        },
        evalReport: {
          summary:
            "v3.0版本底层模型升级效果显著，新增的退货政策和物流查询技能运行稳定，综合性能达到上线标准。",
          overallScore: 84,
          overallScoreTrend: "↑9%",
          metrics: [
            { label: "Skill触发准确率", value: "86%", trend: "↑8%" },
            { label: "任务完成行为率", value: "82%", trend: "↑10%" },
            { label: "结果质量评分", value: "83%", trend: "↑9%" },
            { label: "执行耗时", value: "210ms", trend: "↓15%" },
            { label: "Token消耗量", value: "1590", trend: "↓10%" },
            { label: "回归基准保持率", value: "88%", trend: "↑6%" },
          ],
          testTime: "2026-02-18 10:00",
          testRounds: 5,
          testScenes: ["电商客服", "物流查询", "售后服务"],
          issues: "退货政策查询在跨境场景下响应偏慢，偶发超时。",
          suggestions: "针对跨境退货政策场景增加缓存策略，优化上下文截断阈值。",
          conclusion:
            "v3.0版本整体质量良好，各核心指标均稳步提升，建议发布并重点关注跨境场景的性能表现。",
        },
      },
      {
        version: "2.0.0",
        releaseNote: "增加会员权益咨询和订单状态查询。",
        publishTime: "2026-01-10",
      },
      { version: "1.0.0", releaseNote: "初始版本，基础 FAQ 问答能力。", publishTime: "2025-11-05" },
    ],
    feedbackData: [
      {
        id: "R-1081",
        summary: "用户轮询退货政策",
        source: "线上回流",
        rating: 5,
        toolCallRounds: 3,
        dialogueRounds: 5,
        tokenUsage: 1250,
        enterprise: "星耀电商",
      },
      {
        id: "R-1082",
        summary: "查询物流详情或地址",
        source: "线上回流",
        rating: 4,
        toolCallRounds: 2,
        dialogueRounds: 4,
        tokenUsage: 980,
        enterprise: "星耀电商",
      },
      {
        id: "R-1083",
        summary: "投诉商品质量问题",
        source: "人工标注",
        rating: 1,
        toolCallRounds: 5,
        dialogueRounds: 8,
        tokenUsage: 2100,
        enterprise: "鼎盛科技",
      },
      {
        id: "R-1084",
        summary: "咨询会员权益详情",
        source: "线上回流",
        rating: 5,
        toolCallRounds: 1,
        dialogueRounds: 3,
        tokenUsage: 720,
        enterprise: "鼎盛科技",
      },
      {
        id: "R-1085",
        summary: "修改收货地址请求",
        source: "线上回流",
        rating: 4,
        toolCallRounds: 2,
        dialogueRounds: 3,
        tokenUsage: 650,
        enterprise: "恒通物流",
      },
      {
        id: "R-1086",
        summary: "咨询优惠券使用规则",
        source: "人工标注",
        rating: 5,
        toolCallRounds: 1,
        dialogueRounds: 2,
        tokenUsage: 430,
        enterprise: "恒通物流",
      },
    ],
  },
  {
    id: "agent-002",
    name: "生产排程 Agent",
    version: "2.0.0",
    agentType: "syngent",
    category: "production",
    tags: ["建筑施工", "制造"],
    description:
      "基于约束求解和 AI 预测的智能排程 Agent，适用于离散制造和流程工业，支持多工厂、多产线协同排程和异常自动调整。",
    publisher: "陈蓝",
    publishTime: "2026-03-28",
    iconColor: "#11998e",
    iconText: "产",
    visibility: "public",
    skills: [
      { skillName: "智能排班引擎", version: "1.4.0" },
      { skillName: "数据分析助手", version: "2.0.0" },
    ],
    versions: [
      {
        version: "2.0.0",
        releaseNote: "重构排程引擎，新增多工厂协同和异常自动调整。",
        publishTime: "2026-03-28",
        evolution: {
          skillTriggerAccuracy: "88%",
          skillTriggerAccuracyTrend: "↑10%",
          taskCompletionRate: "85%",
          taskCompletionRateTrend: "↑12%",
          qualityScore: "90%",
          qualityScoreTrend: "↑8%",
          executionTime: "350ms",
          executionTimeTrend: "↓28%",
          tokenUsage: "1890",
          tokenUsageTrend: "↓15%",
          regressionRetention: "93%",
          regressionRetentionTrend: "↑9%",
        },
        evalReport: {
          summary:
            "v2.0版本排程引擎重构后性能大幅提升，多工厂协同调度能力通过验证，异常自动调整覆盖率达到预期。",
          overallScore: 88,
          overallScoreTrend: "↑11%",
          metrics: [
            { label: "Skill触发准确率", value: "88%", trend: "↑10%" },
            { label: "任务完成行为率", value: "85%", trend: "↑12%" },
            { label: "结果质量评分", value: "90%", trend: "↑8%" },
            { label: "执行耗时", value: "350ms", trend: "↓28%" },
            { label: "Token消耗量", value: "1890", trend: "↓15%" },
            { label: "回归基准保持率", value: "93%", trend: "↑9%" },
          ],
          testTime: "2026-03-26 09:00",
          testRounds: 8,
          testScenes: ["单产线排程", "多工厂协同", "紧急插单", "设备故障重排"],
          issues: "在极端多约束场景下求解时间偶尔超过SLA阈值。",
          suggestions: "引入启发式预剪枝策略，减少约束求解空间，提升极端场景的响应速度。",
          conclusion: "v2.0版本达到生产级标准，核心排程能力提升明显，建议发布并在高峰期做好监控。",
        },
      },
      { version: "1.0.0", releaseNote: "初始版本，单产线排程能力。", publishTime: "2026-01-15" },
    ],
    feedbackData: [
      {
        id: "R-2001",
        summary: "排程结果与实际产能偏差",
        source: "线上回流",
        rating: 3,
        toolCallRounds: 4,
        dialogueRounds: 6,
        tokenUsage: 1800,
        enterprise: "华建集团",
      },
      {
        id: "R-2002",
        summary: "紧急插单后重排响应",
        source: "人工标注",
        rating: 4,
        toolCallRounds: 3,
        dialogueRounds: 5,
        tokenUsage: 1450,
        enterprise: "华建集团",
      },
      {
        id: "R-2003",
        summary: "跨产线资源冲突处理",
        source: "线上回流",
        rating: 4,
        toolCallRounds: 5,
        dialogueRounds: 7,
        tokenUsage: 2200,
        enterprise: "锐智制造",
      },
    ],
  },
  {
    id: "agent-003",
    name: "供应链协同 Agent",
    version: "1.5.0",
    agentType: "openclaw",
    category: "supply",
    tags: ["供应链", "采购"],
    description:
      "供应链上下游协同 Agent，实时监控库存水位、自动触发补货、管理供应商绩效评估和交期预警。",
    publisher: "Frontis 官方",
    publishTime: "2026-03-25",
    iconColor: "#f5576c",
    iconText: "供",
    visibility: "public",
    skills: [
      { skillName: "数据分析助手", version: "2.0.0" },
      { skillName: "销售线索评分", version: "1.1.0" },
    ],
    versions: [
      {
        version: "1.5.0",
        releaseNote: "新增供应商绩效自动评估和交期预警。",
        publishTime: "2026-03-25",
        evolution: {
          skillTriggerAccuracy: "85%",
          skillTriggerAccuracyTrend: "↑7%",
          taskCompletionRate: "81%",
          taskCompletionRateTrend: "↑11%",
          qualityScore: "79%",
          qualityScoreTrend: "↑6%",
          executionTime: "245ms",
          executionTimeTrend: "↓20%",
          tokenUsage: "1650",
          tokenUsageTrend: "↓18%",
          regressionRetention: "91%",
          regressionRetentionTrend: "↑8%",
        },
        evalReport: {
          summary:
            "v1.5版本新增的供应商绩效评估和交期预警功能验证通过，库存水位监控响应延迟有改善，整体达标。",
          overallScore: 82,
          overallScoreTrend: "↑8%",
          metrics: [
            { label: "Skill触发准确率", value: "85%", trend: "↑7%" },
            { label: "任务完成行为率", value: "81%", trend: "↑11%" },
            { label: "结果质量评分", value: "79%", trend: "↑6%" },
            { label: "执行耗时", value: "245ms", trend: "↓20%" },
            { label: "Token消耗量", value: "1650", trend: "↓18%" },
            { label: "回归基准保持率", value: "91%", trend: "↑8%" },
          ],
          testTime: "2026-03-23 16:00",
          testRounds: 5,
          testScenes: ["库存监控", "自动补货", "供应商评估", "交期预警"],
          issues: "供应商评分模型在数据稀疏的新供应商上准确度不足。",
          suggestions: "为新供应商引入行业基准默认评分，并在数据积累后逐步切换到个性化模型。",
          conclusion: "v1.5版本功能完整、性能达标，建议发布。重点关注新供应商场景下的评估准确性。",
        },
      },
      {
        version: "1.0.0",
        releaseNote: "初始版本，库存监控和自动补货。",
        publishTime: "2026-02-01",
      },
    ],
    feedbackData: [
      {
        id: "R-3001",
        summary: "补货建议数量偏大",
        source: "线上回流",
        rating: 3,
        toolCallRounds: 2,
        dialogueRounds: 4,
        tokenUsage: 1100,
        enterprise: "盛达供应链",
      },
      {
        id: "R-3002",
        summary: "供应商交期预警不及时",
        source: "人工标注",
        rating: 2,
        toolCallRounds: 3,
        dialogueRounds: 5,
        tokenUsage: 1350,
        enterprise: "盛达供应链",
      },
    ],
  },
  {
    id: "agent-004",
    name: "营销文案 Agent",
    version: "2.3.0",
    agentType: "metaagent",
    category: "sales",
    tags: ["内容创作", "营销"],
    description:
      "全渠道营销内容生产 Agent，覆盖小红书、抖音、公众号、邮件等渠道，支持 A/B 测试文案自动生成和效果追踪。",
    publisher: "王芳",
    publishTime: "2026-03-22",
    iconColor: "#f093fb",
    iconText: "营",
    visibility: "public",
    skills: [
      { skillName: "智能文案生成", version: "3.0.1" },
      { skillName: "DALL-E 图像生成", version: "1.0.0" },
      { skillName: "多语言翻译引擎", version: "2.4.0" },
    ],
    versions: [
      {
        version: "2.3.0",
        releaseNote: "新增 A/B 测试文案对比和效果追踪看板。",
        publishTime: "2026-03-22",
      },
      {
        version: "2.0.0",
        releaseNote: "增加抖音短视频脚本和邮件营销模板。",
        publishTime: "2026-02-10",
      },
      {
        version: "1.0.0",
        releaseNote: "初始版本，小红书和公众号文案生成。",
        publishTime: "2025-12-20",
      },
    ],
    feedbackData: [
      {
        id: "R-4001",
        summary: "小红书文案风格偏正式",
        source: "线上回流",
        rating: 3,
        toolCallRounds: 2,
        dialogueRounds: 3,
        tokenUsage: 890,
        enterprise: "美妆星球",
      },
      {
        id: "R-4002",
        summary: "生成图片与文案不匹配",
        source: "人工标注",
        rating: 2,
        toolCallRounds: 4,
        dialogueRounds: 6,
        tokenUsage: 1800,
        enterprise: "美妆星球",
      },
    ],
  },
  {
    id: "agent-005",
    name: "质量巡检 Agent",
    version: "1.2.0",
    agentType: "syngent",
    category: "production",
    tags: ["质检", "制造"],
    description:
      "基于计算机视觉和传感器数据的智能质量巡检 Agent，支持缺陷识别、SPC 分析和自动生成巡检报告。",
    publisher: "Frontis 官方",
    publishTime: "2026-03-18",
    iconColor: "#764ba2",
    iconText: "质",
    visibility: "public",
    skills: [
      { skillName: "数据分析助手", version: "2.0.0" },
      { skillName: "内容审核自动化", version: "1.5.0" },
    ],
    versions: [
      {
        version: "1.2.0",
        releaseNote: "新增 SPC 控制图分析和报告自动生成。",
        publishTime: "2026-03-18",
      },
      {
        version: "1.0.0",
        releaseNote: "初始版本，缺陷图片识别和分类。",
        publishTime: "2026-01-25",
      },
    ],
    feedbackData: [
      {
        id: "R-5001",
        summary: "微小裂纹漏检",
        source: "人工标注",
        rating: 2,
        toolCallRounds: 3,
        dialogueRounds: 4,
        tokenUsage: 1200,
        enterprise: "锐智制造",
      },
    ],
  },
  /* 团队共享 */
  {
    id: "agent-team-001",
    name: "项目汇报 Agent",
    version: "1.0.0",
    agentType: "openclaw",
    category: "general",
    tags: ["效率", "管理"],
    description:
      "自动收集项目进度数据，生成周报/月报并推送至协作平台，支持自定义汇报模板和多项目并行。",
    publisher: "赵工",
    publishTime: "2026-03-26",
    iconColor: "#4facfe",
    iconText: "汇",
    visibility: "team",
    isSharedToMe: true,
    skills: [
      { skillName: "团队周报自动生成", version: "1.0.0" },
      { skillName: "数据分析助手", version: "2.0.0" },
    ],
    versions: [
      {
        version: "1.0.0",
        releaseNote: "初始版本，项目周报自动生成与推送。",
        publishTime: "2026-03-26",
      },
    ],
    feedbackData: [],
  },
  {
    id: "agent-team-002",
    name: "竞品监控 Agent",
    version: "1.1.0",
    agentType: "metaagent",
    category: "sales",
    tags: ["分析", "营销"],
    description:
      "7x24 小时竞品动态监控 Agent，追踪价格变动、功能更新和市场活动，自动生成差异化策略建议。",
    publisher: "陈蓝",
    publishTime: "2026-03-20",
    iconColor: "#38ef7d",
    iconText: "监",
    visibility: "team",
    isSharedByMe: true,
    skills: [
      { skillName: "竞品分析助手", version: "1.2.0" },
      { skillName: "智能文案生成", version: "3.0.1" },
    ],
    versions: [
      {
        version: "1.1.0",
        releaseNote: "增加市场活动追踪和自动策略建议。",
        publishTime: "2026-03-20",
      },
      {
        version: "1.0.0",
        releaseNote: "初始版本，竞品价格和功能变动监控。",
        publishTime: "2026-02-15",
      },
    ],
    feedbackData: [
      {
        id: "R-T001",
        summary: "竞品价格变动推送延迟",
        source: "线上回流",
        rating: 3,
        toolCallRounds: 1,
        dialogueRounds: 2,
        tokenUsage: 380,
        enterprise: "本团队",
      },
    ],
  },
  /* 我的 Agent */
  {
    id: "agent-mine-001",
    name: "合同风控 Agent",
    version: "1.3.0",
    agentType: "syngent",
    category: "general",
    tags: ["法务", "风控"],
    description:
      "合同全生命周期风控 Agent，自动审核条款、对比历史合同、标注风险点并生成合规建议，减少法务审核工作量。",
    publisher: "陈蓝",
    publishTime: "2026-03-29",
    iconColor: "#434343",
    iconText: "合",
    visibility: "public",
    skills: [
      { skillName: "合同审核流程", version: "1.0.0" },
      { skillName: "知识库问答", version: "2.0.0" },
      { skillName: "GPT-4o 文本模型", version: "1.0.0" },
    ],
    versions: [
      {
        version: "1.3.0",
        releaseNote: "新增历史合同交叉对比和合规建议生成。",
        publishTime: "2026-03-29",
        evolution: {
          skillTriggerAccuracy: "93%",
          skillTriggerAccuracyTrend: "↑11%",
          taskCompletionRate: "91%",
          taskCompletionRateTrend: "↑14%",
          qualityScore: "89%",
          qualityScoreTrend: "↑10%",
          executionTime: "180ms",
          executionTimeTrend: "↓32%",
          tokenUsage: "1580",
          tokenUsageTrend: "↓19%",
          regressionRetention: "97%",
          regressionRetentionTrend: "↑8%",
        },
        evalReport: {
          summary:
            "v1.3版本新增的历史合同对比和合规建议功能表现出色，条款识别准确率显著提升，模型推理速度大幅优化。",
          overallScore: 93,
          overallScoreTrend: "↑12%",
          metrics: [
            { label: "Skill触发准确率", value: "93%", trend: "↑11%" },
            { label: "任务完成行为率", value: "91%", trend: "↑14%" },
            { label: "结果质量评分", value: "89%", trend: "↑10%" },
            { label: "执行耗时", value: "180ms", trend: "↓32%" },
            { label: "Token消耗量", value: "1580", trend: "↓19%" },
            { label: "回归基准保持率", value: "97%", trend: "↑8%" },
          ],
          testTime: "2026-03-27 11:00",
          testRounds: 7,
          testScenes: ["标准合同审核", "合同条款对比", "风险条款标注", "合规建议生成"],
          issues: "对于非标准格式的扫描件合同，OCR提取准确率有待提升。",
          suggestions: "集成高精度OCR预处理模块，增加文档版面分析能力。",
          conclusion:
            "v1.3版本各项指标均超出预期，建议正式发布。后续迭代重点提升非标文档的处理能力。",
        },
      },
      {
        version: "1.1.0",
        releaseNote: "增加风险等级评估和自动摘要。",
        publishTime: "2026-02-25",
        evolution: {
          skillTriggerAccuracy: "84%",
          skillTriggerAccuracyTrend: "↑6%",
          taskCompletionRate: "80%",
          taskCompletionRateTrend: "↑8%",
          qualityScore: "81%",
          qualityScoreTrend: "↑7%",
          executionTime: "265ms",
          executionTimeTrend: "↓12%",
          tokenUsage: "1950",
          tokenUsageTrend: "↓8%",
          regressionRetention: "90%",
          regressionRetentionTrend: "↑5%",
        },
        evalReport: {
          summary: "v1.1版本新增风险等级评估功能通过验证，自动摘要准确性尚可，整体满足上线要求。",
          overallScore: 82,
          overallScoreTrend: "↑7%",
          metrics: [
            { label: "Skill触发准确率", value: "84%", trend: "↑6%" },
            { label: "任务完成行为率", value: "80%", trend: "↑8%" },
            { label: "结果质量评分", value: "81%", trend: "↑7%" },
            { label: "执行耗时", value: "265ms", trend: "↓12%" },
            { label: "Token消耗量", value: "1950", trend: "↓8%" },
            { label: "回归基准保持率", value: "90%", trend: "↑5%" },
          ],
          testTime: "2026-02-23 15:30",
          testRounds: 5,
          testScenes: ["标准合同审核", "风险等级评估", "合同摘要生成"],
          issues: "长篇合同（超过50页）的摘要会遗漏部分次要条款。",
          suggestions: "优化长文档分段策略，确保摘要覆盖所有关键和次要条款。",
          conclusion: "v1.1版本基本达标，建议发布并在后续版本中优化长文档处理能力。",
        },
      },
      {
        version: "1.0.0",
        releaseNote: "初始版本，合同关键条款提取和基础风险标注。",
        publishTime: "2026-01-20",
      },
    ],
    feedbackData: [
      {
        id: "R-M001",
        summary: "合同违约条款识别遗漏",
        source: "人工标注",
        rating: 2,
        toolCallRounds: 4,
        dialogueRounds: 6,
        tokenUsage: 2300,
        enterprise: "华建集团",
      },
      {
        id: "R-M002",
        summary: "标准合同审核通过",
        source: "线上回流",
        rating: 5,
        toolCallRounds: 2,
        dialogueRounds: 3,
        tokenUsage: 980,
        enterprise: "华建集团",
      },
      {
        id: "R-M003",
        summary: "供应商合同条款对比",
        source: "线上回流",
        rating: 4,
        toolCallRounds: 3,
        dialogueRounds: 5,
        tokenUsage: 1560,
        enterprise: "盛达供应链",
      },
      {
        id: "R-M004",
        summary: "知识产权条款风险提醒",
        source: "人工标注",
        rating: 5,
        toolCallRounds: 2,
        dialogueRounds: 4,
        tokenUsage: 1100,
        enterprise: "盛达供应链",
      },
      {
        id: "R-M005",
        summary: "续约合同差异分析",
        source: "线上回流",
        rating: 4,
        toolCallRounds: 3,
        dialogueRounds: 4,
        tokenUsage: 1280,
        enterprise: "锐智制造",
      },
    ],
  },
  {
    id: "agent-mine-002",
    name: "智能排班 Agent",
    version: "1.2.0",
    agentType: "openclaw",
    category: "production",
    tags: ["调度", "制造"],
    description:
      "面向多班次制造业的智能排班 Agent，综合员工技能、法规约束和产能需求自动生成最优班次方案。",
    publisher: "陈蓝",
    publishTime: "2026-03-24",
    iconColor: "#00f2fe",
    iconText: "排",
    visibility: "team",
    skills: [
      { skillName: "智能排班引擎", version: "1.4.0" },
      { skillName: "数据分析助手", version: "2.0.0" },
    ],
    versions: [
      {
        version: "1.2.0",
        releaseNote: "新增法规约束自动检测和弹性工时模式。",
        publishTime: "2026-03-24",
      },
      {
        version: "1.0.0",
        releaseNote: "初始版本，基于固定规则的排班生成。",
        publishTime: "2026-02-05",
      },
    ],
    feedbackData: [
      {
        id: "R-M101",
        summary: "加班上限超标未告警",
        source: "线上回流",
        rating: 3,
        toolCallRounds: 2,
        dialogueRounds: 3,
        tokenUsage: 780,
        enterprise: "锐智制造",
      },
    ],
  },
];

/**
 * AI 专家工作空间（进化实验室）。
 */
export const WORKBENCH_AGENT_WORKSPACES: WorkbenchAgentWorkspace[] = [
  {
    id: "ws-001",
    name: "智能客服 Agent",
    description:
      "面向电商和 SaaS 企业的全渠道智能客服 Agent，集成退货政策查询、物流追踪、会员权益咨询等技能。",
    iconColor: "#667eea",
    iconText: "客",
    framework: "MetaAgent",
    skillCount: 3,
    skills: [
      { name: "智能文案生成", version: "3.0.1" },
      { name: "多语言翻译引擎", version: "2.4.0" },
      { name: "知识库问答", version: "2.0.0" },
    ],
    createdAt: "2026-03-15",
    fileCount: 16,
    overviewText:
      "本空间共有 16 个文件，围绕智能客服 Agent 展开，包含产品架构、业务规划、合作汇报、产业落地、政策解析等，材料类型含 PPT、讲稿、讨论文档等。",
    conversations: [
      {
        id: "conv-01",
        title: "用户询问OPC服务回复撰写",
        summary: "FrontisAI里面有一个工作台，是专...",
        date: "56分钟前",
      },
      {
        id: "conv-02",
        title: "昌发展OPC方案优化建议",
        summary: "你梳理的PPT框架特别的好。接下来请...",
        date: "3月24日",
      },
      {
        id: "conv-03",
        title: "PPT修改建议整理",
        summary: "附件中是目前生成的第二章标题页，其...",
        date: "3月15日",
      },
      {
        id: "conv-04",
        title: '昌平"1+2+N"AI产业体系是什么',
        summary: "现在昌平区的人工智能发展战略基本了...",
        date: "3月14日",
      },
      {
        id: "conv-05",
        title: "徐广新汇报OPC进展",
        summary: "汇报下OPC方向的最新进展和思考...",
        date: "2月26日",
      },
      {
        id: "conv-06",
        title: "梳理OPC方案及会议核心",
        summary: "方案没有任何问题，帮我生成这个方案...",
        date: "2月26日",
      },
      {
        id: "conv-07",
        title: "syngents会见政府方案框架...",
        summary: "重新生成PPT框架",
        date: "2月24日",
      },
    ],
    knowledgeBases: [
      { id: "kb-01", name: "OPC产业政策文库", fileCount: 32 },
      { id: "kb-02", name: "客服场景最佳实践", fileCount: 18 },
      { id: "kb-03", name: "产品技术文档", fileCount: 45 },
    ],
    feedbackData: [
      { enterprise: "华建集团", count: 2 },
      { enterprise: "锐智制造", count: 1 },
    ],
    results: [
      { id: "res-01", title: "用户询问OPC服务回复撰写", resultCount: 3, lastDate: "56分钟前" },
      { id: "res-02", title: "昌发展OPC方案优化建议", resultCount: 54, lastDate: "3月24日" },
      { id: "res-03", title: "PPT修改建议整理", resultCount: 5, lastDate: "3月15日" },
      { id: "res-04", title: '昌平"1+2+N"AI产业体系是...', resultCount: 3, lastDate: "3月14日" },
      { id: "res-05", title: "徐广新汇报OPC进展", resultCount: 15, lastDate: "2月26日" },
      { id: "res-06", title: "梳理OPC方案及会议核心", resultCount: 6, lastDate: "2月26日" },
      { id: "res-07", title: "syngents会见政府方案框...", resultCount: 8, lastDate: "2月24日" },
    ],
  },
  {
    id: "ws-002",
    name: "供应链协同 Agent",
    description: "供应链全链路协同 Agent，覆盖采购计划、库存监控、物流调度和供应商管理。",
    iconColor: "#11998e",
    iconText: "供",
    framework: "Syngent",
    skillCount: 4,
    skills: [
      { name: "采购计划生成", version: "2.1.0" },
      { name: "库存异常监控", version: "1.8.0" },
      { name: "物流调度优化", version: "1.5.0" },
      { name: "供应商评估", version: "1.2.0" },
    ],
    createdAt: "2026-03-18",
    fileCount: 12,
    overviewText:
      "本空间围绕供应链协同 Agent 展开，包含采购、库存、物流和供应商管理相关的设计方案和配置文件。",
    conversations: [
      {
        id: "conv-s01",
        title: "采购计划自动生成方案",
        summary: "基于历史数据和季节趋势生成采购计划...",
        date: "3月20日",
      },
      {
        id: "conv-s02",
        title: "库存异常监控规则配置",
        summary: "设置安全库存阈值和预警触发条件...",
        date: "3月18日",
      },
    ],
    knowledgeBases: [
      { id: "kb-s01", name: "供应链管理文库", fileCount: 28 },
      { id: "kb-s02", name: "物流行业标准", fileCount: 15 },
    ],
    feedbackData: [
      { enterprise: "极客供应链", count: 3 },
      { enterprise: "百汇零售", count: 2 },
    ],
    results: [
      { id: "res-s01", title: "采购计划自动生成方案", resultCount: 8, lastDate: "3月20日" },
      { id: "res-s02", title: "库存异常监控规则配置", resultCount: 4, lastDate: "3月18日" },
    ],
  },
  {
    id: "ws-003",
    name: "数据分析 Agent",
    description: "企业级数据分析 Agent，支持自然语言查询、自动报表生成、趋势预测和异常检测。",
    iconColor: "#a855f7",
    iconText: "析",
    framework: "OpenClaw",
    skillCount: 3,
    skills: [
      { name: "数据分析助手", version: "2.0.0" },
      { name: "SQL 生成器", version: "1.6.0" },
      { name: "可视化引擎", version: "1.3.0" },
    ],
    createdAt: "2026-03-20",
    fileCount: 9,
    overviewText: "本空间围绕数据分析 Agent 展开，包含 SQL 查询、报表模板和可视化配置。",
    conversations: [
      {
        id: "conv-d01",
        title: "自然语言转SQL查询方案",
        summary: "设计自然语言到SQL的转换流程...",
        date: "3月22日",
      },
    ],
    knowledgeBases: [{ id: "kb-d01", name: "数据分析方法论", fileCount: 20 }],
    feedbackData: [{ enterprise: "新锐科技", count: 2 }],
    results: [
      { id: "res-d01", title: "自然语言转SQL查询方案", resultCount: 6, lastDate: "3月22日" },
    ],
  },
  {
    id: "ws-004",
    name: "HR 招聘助手 Agent",
    description:
      "面向多班次制造业的智能排班 Agent，综合员工技能、法规约束和产能需求自动生成最优班次方案。",
    iconColor: "#00f2fe",
    iconText: "招",
    framework: "MetaAgent",
    skillCount: 2,
    skills: [
      { name: "简历解析引擎", version: "1.4.0" },
      { name: "智能匹配推荐", version: "1.1.0" },
    ],
    createdAt: "2026-03-22",
    fileCount: 8,
    overviewText: "本空间围绕 HR 招聘助手 Agent 展开，包含简历解析和岗位匹配相关配置。",
    conversations: [
      {
        id: "conv-h01",
        title: "简历解析规则优化",
        summary: "优化简历关键信息提取准确率...",
        date: "3月25日",
      },
    ],
    knowledgeBases: [{ id: "kb-h01", name: "HR行业知识库", fileCount: 12 }],
    feedbackData: [{ enterprise: "创新医疗", count: 1 }],
    results: [{ id: "res-h01", title: "简历解析规则优化", resultCount: 3, lastDate: "3月25日" }],
  },
  {
    id: "ws-005",
    name: "销售增长 Agent",
    description: "销售增长 Agent，集成线索评分、跟进提醒、战报生成和客户画像分析。",
    iconColor: "#f5576c",
    iconText: "销",
    framework: "Syngent",
    skillCount: 3,
    skills: [
      { name: "线索评分引擎", version: "2.0.0" },
      { name: "客户画像分析", version: "1.5.0" },
      { name: "战报生成", version: "1.2.0" },
    ],
    createdAt: "2026-03-25",
    fileCount: 11,
    overviewText: "本空间围绕销售增长 Agent 展开，包含线索管理、客户画像和战报模板。",
    conversations: [
      {
        id: "conv-sl01",
        title: "线索评分模型设计",
        summary: "设计多维度线索打分模型...",
        date: "3月28日",
      },
      {
        id: "conv-sl02",
        title: "客户画像分析方案",
        summary: "基于行为数据构建客户画像...",
        date: "3月26日",
      },
    ],
    knowledgeBases: [{ id: "kb-sl01", name: "销售方法论", fileCount: 22 }],
    feedbackData: [
      { enterprise: "智联制造", count: 2 },
      { enterprise: "环球电商", count: 1 },
    ],
    results: [
      { id: "res-sl01", title: "线索评分模型设计", resultCount: 7, lastDate: "3月28日" },
      { id: "res-sl02", title: "客户画像分析方案", resultCount: 4, lastDate: "3月26日" },
    ],
  },
  {
    id: "ws-006",
    name: "内容创作 Agent",
    description: "企业内容创作 Agent，支持公众号文章、产品文案、营销邮件和社交媒体内容的自动生成。",
    iconColor: "#fbc2eb",
    iconText: "创",
    framework: "OpenClaw",
    skillCount: 4,
    skills: [
      { name: "智能文案生成", version: "3.0.1" },
      { name: "多语言翻译引擎", version: "2.4.0" },
      { name: "SEO 优化助手", version: "1.3.0" },
      { name: "配图推荐", version: "1.0.0" },
    ],
    createdAt: "2026-03-28",
    fileCount: 14,
    overviewText: "本空间围绕内容创作 Agent 展开，包含文案生成、翻译、SEO优化和配图推荐。",
    conversations: [
      {
        id: "conv-c01",
        title: "公众号文章生成模板",
        summary: "设计适配不同行业的文章模板...",
        date: "3月30日",
      },
      {
        id: "conv-c02",
        title: "营销邮件自动化方案",
        summary: "设计邮件自动化触发规则...",
        date: "3月29日",
      },
    ],
    knowledgeBases: [
      { id: "kb-c01", name: "内容营销知识库", fileCount: 35 },
      { id: "kb-c02", name: "品牌文案风格指南", fileCount: 8 },
    ],
    feedbackData: [{ enterprise: "百汇零售", count: 3 }],
    results: [
      { id: "res-c01", title: "公众号文章生成模板", resultCount: 12, lastDate: "3月30日" },
      { id: "res-c02", title: "营销邮件自动化方案", resultCount: 5, lastDate: "3月29日" },
    ],
  },
];
